### PR TITLE
german localization

### PR DESCRIPTION
**Pull request by roe-dl**
This refers to https://github.com/poblabs/weewx-belchertown/issues/830

### CODE REVIEW

**Comment by norecords** [comment]
@roe-dl can i use your file as a skeleton for french translation ?

**Comment by roe-dl** [comment]
@norecords Yes, of course.

**Comment by olpayras** [comment]
> @roe-dl can i use your file as a skeleton for french translation ?

Tkanks a lot @roe-dl for sharing. @norecords : very interested if you have a french translation. ;) I can share you my weewx.conf translation, if you want do compare tasks. Olivier.

**Comment by norecords** [comment]
@olpayras I'll open a PR asap. I will need your translation (and others if there are) to compare with mine. I'll notice you ;)

**Comment by olpayras** [comment]
@norecords : Ok for that. Tell me when it will be opened. I'll send you my translation. They are probably perfectible,

**Pull request merged**
