### PR TITLE
sun&moon - more space for translation

### PR DESCRIPTION
**Pull request by jovo0911**
a small change gives more space for translation:
from:

 div class="row small-almanac"
 ....
 div class="col-sm-6 sun"
....
 div class="col-sm-6 sun"

to:

 div class="row small-almanac"
...
 div class="col-sm-5 sun"
....
 div class="col-sm-7 sun"

### CODE REVIEW

**Comment by poblabs** [comment]
Hi jovo, Is this a pull request or a suggestion? I ask because it doesn't show any commits. If just a suggestion, I'll close this and manually merge the changes.

**Comment by jovo0911** [comment]
Hi Pat,

it's a suggestion, so please close. Sorry but „GitHub“ is not my favorite ;-))

So where is a better place for „suggestion“? It’s complicated if you not work every day with GitHub.

Thank you for your help.

regards
Joachim Vorrath


 


> Am 06.07.2020 um 15:11 schrieb poblabs <notifications@github.com>:
> 
> Hi jovo, Is this a pull request or a suggestion? I ask because it doesn't show any commits. If just a suggestion, I'll close this and manually merge the changes.
> 
>

**Comment by poblabs** [comment]
No problem! Usually in the "issues" area for suggestions (even though it says issues). I will close this and update the code with your suggestions!

**Comment by jovo0911** [comment]
OK - next time in „issues“ - i’ll do ;-)

I updated the code for me times before, for more space. Have no trouble with that.

regards

**Pull request closed without merging**
