### PR TITLE
Aeris AQI and AQI chart option

### PR DESCRIPTION
**Pull request by uajqq**
Opening a new pull request to replace the old; all of my tinkering had led to a messy commit history, and my linter removed a bunch of trailing whitespace, leading to hundreds of tiny changes. Sorry about that.

**This pull request adds Air Quality Index information from the Aeris weather forecast API. Forecast must be enabled and set to Aeris for it to work, and the AQI display has to be manually turned on (see below).**

Features:

- AQI is displayed along with the current AQI description. Color automatically changes to reflect AQI. Colors are taken from the official standard, with some adjustments to better match the skin template.
- AQI is read from the nearest AQI station within 25 miles of the weather station's reported position. If no AQI station within 25 miles is available, no AQI will be displayed.
- Users can select whether or not to display AQI. **AQI is turned off by default. Add `aqi_enabled = 1` to the same section as `forecast_enabled` to turn it on.**
- Users can use their own labels for the AQI description. This allows other languages than English to be displayed. The example below shows how you would set it if you wanted French labels. If this section is not set, default US-EPA 2016 standard phrasing will be used automatically. 
```
[StdReport]
    [[Belchertown]]
        [[[Labels]]]
            [[[[Generic]]]]
                aqi_good = bon
                aqi_moderate = modéré
                aqi_usg = mauvais pour certains
                aqi_unhealthy = mauvais
                aqi_very_unhealthy = très mauvais
                aqi_hazardous = dangereux
```
- Users can add a chart to display AQI graphically if they wish. The chart also changes color to match the AQI, and displays the AQI description. Example config:
```
    [[currentAQI]]
        title = Air Quality Index
        [[[aqiChart]]]
```

Here's how it looks:
Screen Shot 2020-12-19 at 1 20 08 PM

Screen Shot 2020-12-19 at 1 20 27 PM

Screen Shot 2020-12-19 at 1 22 37 PM

Screen Shot 2020-12-19 at 1 24 32 PM

### CODE REVIEW

**Comment by Distortionist** [comment]
Can this be configured to read the AQI reading from our personal sensors? I don't mind if it gets it from Aries as long as it is the reading I sent them.

Thank you for this, it is much needed and a great addition, especially if it can be adapted to get the reading from my sensor instead of Aeries.

**Comment by uajqq** [comment]
That depends on how your sensor is reporting the data. Is it going to a separate database, or weewx?

**Comment by Distortionist** [comment]
Weewx! Weewx sees and reports the sensor readings.

**Comment by uajqq** [comment]
Does your sensor report AQI, or one of the readings used to calculate AQI, like pm2_5 or something similar? If it reports AQI, it could probably be graphed/reported easily. If not, AQI would need to be calculated, and that's more difficult. There are different formulas depending on which country you're in.

**Comment by Distortionist** [comment]
Yes, it does. It has both AQI and PM2_5!

**Comment by ddperso** [comment]
> Can this be configured to read the AQI reading from our personal sensors? I don't mind if it gets it from Aries as long as it is the reading I sent them.
> 
> Thank you for this, it is much needed and a great addition, especially if it can be adapted to get the reading from my sensor instead of Aeries.

Hi distortionist
Which sensor do you use? I am interesting by ozon sensor.

**Comment by Distortionist** [comment]
Its an ambient weather sensor for my ws2000 station.

**Comment by Distortionist** [comment]
I really like what you did there. It would be awesome if there was an option to get it from Aeries or locally, and read the pm2_5 reading stored in weewx database from the sensor. Thank you for your efforts!

**Comment by Distortionist** [comment]
I can't for the life of me figure out how to merge this pull request to try it. Documentation says I should have a merge button but I don't. Sorry I am such a newb to this, but can you point me in the right direction so I can try what you did?

**Comment by uajqq** [comment]
For the time being, you can 'git clone' my fork, then 'git checkout aqi' to switch to that branch. Then install the extension as you would normally and restart weewx. Wait for an archive interval to see the changes. If you want to go back to a stable version, you can 'git checkout master' and reinstall the extension, since my fork's "master" branch is identical to poblabs'.

**Comment by poblabs** [comment]
I think this looks good, thanks for your help!!

**Comment by poblabs** [comment]
@uajqq Could you do me a favor? Add a new pull request with the skin.conf changes and the config updates documented within readme.md?

**Comment by uajqq** [comment]
> @uajqq Could you do me a favor? Add a new pull request with the skin.conf changes and the config updates documented within readme.md?

Right, of course, forgot about that...stand by

**Comment by poblabs** [comment]
No worries - thanks!

**Comment by uajqq** [comment]
> I really like what you did there. It would be awesome if there was an option to get it from Aeries or locally, and read the pm2_5 reading stored in weewx database from the sensor. Thank you for your efforts!

I’ve just created a pull request that should do what you’re looking for. It’s not as quick to set up as the AQI graph, but it should allow you to graph your own AQI/pm2_5 and have the colors adjust accordingly. You can graph any value you’d like, not just AQI. In your case, here would be an example config to graph particulate matter 2.5 (PM2_5) and color-code according to health ratings:
```
[[exampleGauge]]
    title = Example air quality (particulate matter PM2.5)
    type = gauge
    [[[pm2_5]]]                                                                                                                        
            rounded = 1      
            colors_enabled = 1                                                                                                                
            color1_position = 12.1                                                                                                              
            color1 = "#71bc3c" # Good                                                                                                               
            color2_position = 35.4                                                                                                              
            color2 =  "rgba(255,174,0,0.9)" # Moderate                                                                                                       
            color3_position = 55.4                                                                                                             
            color3 = "rgba(255,127,0,1)" # Unhealthy for sensitive groups                                                                                                               
            color4_position = 150.4                                                                                                             
            color4 = "rgba(255,69,69,1)"  # Unhealthy                                                                                                             
            color5_position = 250.4                                                                                                             
            color5 = "#b16286" # Very unhealthy                                                                                                              
            color6_position = 350.4                                                                                                             
            color6 = "#cc241d"  # Hazardous                                                                                                             
            yAxis_min = 0
            yAxis_max = 500
```

**Comment by Distortionist** [comment]
> > I really like what you did there. It would be awesome if there was an option to get it from Aeries or locally, and read the pm2_5 reading stored in weewx database from the sensor. Thank you for your efforts!
> 
> I’ve just created a pull request that should do what you’re looking for. It’s not as quick to set up as the AQI graph, but it should allow you to graph your own AQI/pm2_5 and have the colors adjust accordingly. You can graph any value you’d like, not just AQI. In your case, here would be an example config to graph particulate matter 2.5 (PM2_5) and color-code according to health ratings:
> 
> ```
> [[exampleGauge]]
>     title = Example air quality (particulate matter PM2.5)
>     type = gauge
>     [[[pm2_5]]]                                                                                                                        
>             rounded = 1      
>             colors_enabled = 1                                                                                                                
>             color1_position = 12.1                                                                                                              
>             color1 = "#71bc3c" # Good                                                                                                               
>             color2_position = 35.4                                                                                                              
>             color2 =  "rgba(255,174,0,0.9)" # Moderate                                                                                                       
>             color3_position = 55.4                                                                                                             
>             color3 = "rgba(255,127,0,1)" # Unhealthy for sensitive groups                                                                                                               
>             color4_position = 150.4                                                                                                             
>             color4 = "rgba(255,69,69,1)"  # Unhealthy                                                                                                             
>             color5_position = 250.4                                                                                                             
>             color5 = "#b16286" # Very unhealthy                                                                                                              
>             color6_position = 350.4                                                                                                             
>             color6 = "#cc241d"  # Hazardous                                                                                                             
>             yAxis_min = 0
>             yAxis_max = 500
> ```

Thant is fantastic! Thank you so much, it is the only change I have done so far. I have not merged anything else into my version of Belchertown yet, i did add that graph and I do think it will do what I want, but for some reason it is blank at the moment. The only changes I made are to the title and renamed exampleguage to chart9.  Here it is if you want to see it, I see the chart, and my pm2_5 readings are working as you can see on the other chart, it just has no reading! Any idea?

**Comment by uajqq** [comment]
>I see the chart, and my pm2_5 readings are working as you can see on the other chart, it just has no reading! Any idea? livingstonecove.ca

If you haven't updated the skin, it won't have the machinery to display the chart properly. You need to get the version of the skin from my `gauge` branch installed first.

`git clone https://github.com/uajqq/weewx-belchertown`
`cd weewx-belchertown`
`git checkout gauge`
`sudo [path to weewx]/bin/wee_extension --install [path to weewx-belchertown folder you just downloaded]`

**Comment by Distortionist** [comment]
Alright, I followed your instructions and the install went smoothly, except now I get errors generating graphs, here is the error. Everything other than the chart seems working still so I can just ignore this error while we troubleshoot.

Here is what I get, I will try using that example graph
`Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****  'aqi'
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      obj.start()
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      self.run()
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      default_binding)
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1033, in get_extension_list
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****      aqi = data['aqi'][0]['response'][0]['periods'][0]['aqi']
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****  KeyError: 'aqi'
Dec 26 21:02:19 LivingstoneCove weewx[12248] ERROR weewx.reportengine:         ****  Generator terminated
`
I get that error even with or without aqi_enabled = 1 and with the example graph you gave me there, or commented out.

**Comment by Distortionist** [comment]
I lied, my station website is not updating. It is no big deal, I will wait for a response or revert to previous version if it bugs me. I would like to help troubleshoot it so it works for everyone.

**Comment by Distortionist** [comment]
The error seems to have changed from KeyError, to IndexError: list index out of range. Here is the full error

`Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****  list index out of range
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      obj.start()
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      self.run()
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      default_binding)
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1033, in get_extension_list
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****      aqi = data['aqi'][0]['response'][0]['periods'][0]['aqi']
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****  IndexError: list index out of range
Dec 26 21:24:31 LivingstoneCove weewx[14165] ERROR weewx.reportengine:         ****  Generator terminated
`

**Comment by poblabs** [comment]
#490 has been merged into the master branch

**Comment by WiggyToo** [comment]
Hi - just stumbled across this after tracking an error with AQI having upraded to WEEWX 5 and latest 1.3.1 skin, forgive my ignorance but in the post above it says users can add this chart:
```

    [[currentAQI]]
        title = Air Quality Index
        [[[aqiChart]]]


```

Is that the case and if so where is the best place to add this code snippet?

Site is here

https://www.wiggytoo.co.uk/

Thanks in advance,
Gav

**Comment by uajqq** [comment]
Yes, adding that snippet will insert a simple gauge showing the current AQI (taken from Aeris Weather). You can insert it anywhere you wish in the `graphs.conf` file -- see the Charts section of the wiki.

**Comment by WiggyToo** [comment]
Great, thanks for the pointer.

Gav

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
