### PR TITLE
Hourly and three-hourly forecasts (#338)

### PR DESCRIPTION
**Pull request by michaelundwd**
This is the PR for  #338 

This PR contains five modified files to enable one of three different forecasts to be selected and displayed.  The forecasts are denoted by the hourly intervals between forecasts; 1 or 3 or 24.

 skin.conf contains three new items to handle their configuration.

1) forecast defaults: forecast_interval_hours, which can take one of four values: 0, 1, 3, 24.
    0 has the effect of hiding the forecasts completely, but allows forecast alerts to be shown - see #404
    1, 3 and 24 specify the interval between forecasts; 24 is the original (daily) forecast
2)  label: forecast_interval_caption is the label ahead of the 1, 3 and 24 hr selection buttons
3)  moment.js label: time_forecast_time specifies the format of day and time for 1hr and 3hr forecasts.  There is no need to change this as it is locale-dependent.

The consequence of these changes is that there are now five calls to aeris api every hour, compared to the original three.  
The updating of the forecasts is still every hour, but the code has been modified to move the time within the hour to the beginning of the hour, so the 1 hour forecast is always in the future.

Outstanding:
I have not yet addressed the issue of how to make the forecasts work properly in responsive mode for smaller screens.

### CODE REVIEW

**Comment by ArendPWS** [comment]
@michaelundwd 

Nice add-on! 👍 Have it up and running.

Nieuwe verwachting Aeris Belchertown

Maybe you can add some extra debug info? It is really handy when the contents of the JSONs is displayed in the console. Added the line belchertown_debug(data) like this:

	function update_forecast_data( data ) {
		forecast_provider = "$Extras.forecast_provider";
		belchertown_debug("Forecast: Provider is " + forecast_provider);
		belchertown_debug("Forecast: Updating data");
		belchertown_debug(data);

Verwachting JSON console

**Comment by michaelundwd** [comment]
@ArendPWS 

Glad you like it, and pleased to see it working in a translated version.  Thanks for the debug hint.
I notice you have added the gust and km/h to the wind readings.  I decided against that when I had some very strong winds when I was testing that overflowed the row without making it too small.  Be interested to know how you formatted it.

Michael

**Comment by fvirgola80** [comment]
good morning, I am very interested in this solution it is done very well. I have the version of Belchertown 1.2 how can I implement this type of visualization? Will I just replace the files? weewx version is 3.9.2 and my website is www.meteocivitavecchia.it Thanks

**Comment by michaelundwd** [comment]
The solution is based on Belchertown 1.2 and I am running weewx 3.9.1. so you should be ok just replacing the five files that I changed. There are only three additions to skin.conf, so you might do those manually to your existing version.  As usual make sure you have backup copies just in case.  Probably best to restart weewx when you have made the changes.
Michael

**Comment by fvirgola80** [comment]
Thanks for the reply michaelundwd, could you kindly create me a zip file or a tar with the 5 files if you can.
Thank you so much

**Comment by michaelundwd** [comment]
You should be able to get the files directly from github as follows:  I'm still struggling with how github works, so this may not be the best method.

1. Assuming you are at https://github.com/poblabs/weewx-belchertown, click on the Pull Requests link
2. Click on PR #455 Hourly and three-hourly forecasts (#338)
3. You will see the commits are in michaelundwd: 1.2_forecast - click on this
4. Click on the green Code button and Download ZIP
5. Open the zip file and you will find the files in the bin and skin folders. 

Michael

**Comment by fvirgola80** [comment]
Thanks a lot michaelundwd, the files have been downloaded, I will not replace them soon I tell you how it goes.
thanks a lot

**Comment by ArendPWS** [comment]
> Glad you like it, and pleased to see it working in a translated version. Thanks for the debug hint.
> I notice you have added the gust and km/h to the wind readings. I decided against that when I had some very strong winds when I was testing that overflowed the row without making it too small. Be interested to know how you formatted it.
> 
> Michael

Hi @michaelundwd . Yes, I noticed you commented out some code, so have been playing around with it a bit. Will see how it works out with high numbers on windspeed. I am not using the standard width of the skin but have changed that into 1600px. Also did some tweaks on your CSS of the forecast classes and changed its width to match the 1600px. That's the beauty of this skin: change it anyway you like 🙂 

	.site-inner,
	.wrap {
		margin: 0 auto;
		/*max-width: 1200px;*/
		max-width: 1600px;
	}

**Comment by fvirgola80** [comment]
Good evening,
I configured the belkertown skin according to the changes to the 5 files listed by @michaelundwd with which I congratulate myself for the excellent job.
The visualization on pc is perfect in fact as you can see www.meteocivitavecchia.it, instead from a smartphone some configuration is lost
As you can see, the weather information settings are shifted from and before
second
the following images show you how the 1 hour forecasts are completely outlined, while the three and 24 hour forecasts are perfect.
What should be configured to have the correct display of wind information and 1 hour forecasts on a smartphone or tablet.
Thanks
Screenshot_2020-11-05-15-51-50-353_com android chrome
Screenshot_2020-11-05-15-52-01-057_com android chrome
Screenshot_2020-11-05-15-52-07-736_com android chrome
Screenshot_2020-11-05-15-52-13-170_com android chrome
Screenshot_2020-11-05-15-52-19-138_com android chrome

**Comment by michaelundwd** [comment]
I am working on the responsive mode for the 1 hour forecasts, so will update you as soon as I have a good-looking solution. The vertical display of the temperatures does not work well on a narrow screen, and there are 16 of them! 
I think the wind information is a reported issue, but I can't find which one.
Michael

**Comment by fvirgola80** [comment]
Thanks a lot @michaelundwd if I can help you I would be happy. This visualization is wonderful you have been very good. My email address is fvirgola80@gmail.com
Thanks

**Comment by ArendPWS** [comment]
@michaelundwd 

I solved the problem with the CSS on small screens with this code (in the @media only screen and (max-width: 800px) section):

    .forecast-conditions img, .forecast-image img {
        width:30%;
        height:auto;
    }

Maybe something similar could work for the .pi section?

I found an error regarding the calculation of windspeed:

                // Determine wind units
                if ( "$Extras.forecast_units" == "ca" ) {
                    // ca = kph
                    windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedKPH"];
                    windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustKPH"];
                } else if ( "$Extras.forecast_units" == "si" ) {
                    // si = meters per second. MPS is KPH / 3.6
                    //windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedKPH"] / 3.6;
                    //windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustKPH"] / 3.6;
                    windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedKPH"];
                    windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustKPH"];					
                } else {
                    // us and uk2 and default = mph
                    windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedMPH"];
                    windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustMPH"];
                }

The configuration of "si" units needs to provide km/h wind.

I also added units for temperature. You can check the results on my test site (still/allways under construction 😉 ) here:

[hengelo.rf.gd/belchertown](hengelo.rf.gd/belchertown)

**Comment by fvirgola80** [comment]
Fantastic @ArnedPWS could you kindly tell me which file I should modify to get the correct result for the wind display and the forecast to 1 you modified? thank you so much

**Comment by michaelundwd** [comment]
@ArendPWS, @fvirgola80 
Could you take a look at http://lordshipweather.uk/hourly for my attempt at a reasonable layout for narrow 1 hourly forecasts please?  If it's ok, I will issue a revised PR when I find out how to do it!
Michael

**Comment by fvirgola80** [comment]
@michael is now perfect both in the single hour and in the three hours and twenty-four, I saw that you added the bars below it is cleaner and clearer ... great job. We need to ask @Arend how he managed to fix the wind up.
If you tell me what and which files you changed of the skin as soon as I leave work, I will try it too.
thanks a lot
IMG_20201106_163455
IMG_20201106_163519

**Comment by ddperso** [comment]
Great job!
Could you update your PR, I would like try it with several configurations (mobile, Ipad, PC)

**Comment by poblabs** [comment]
Looks awesome! Once it's updated and everyone's happy, I'll merge

**Comment by michaelundwd** [comment]
Have just updated the PR version (1.2_forecast) with changes to 2 files to handle responsive mode for 1-hour forecast:
1  belchertown.js.tmpl; also removed blank lines and added debugging - thanks @ArendPWS 
2  style.css
Thanks for feedback so far
Michael

**Comment by fvirgola80** [comment]
great job michael I await cob anxious the files to be edited very good would the wind always remain to be fixed?

**Comment by ArendPWS** [comment]
@michaelundwd 
Well done Michael 👍 

@fvirgola80 
If you are using "si" units (forecast_units) but want the windspeed in the forecast to be  displayed in km/h make these changes:

            // Determine wind units
            if ( "$Extras.forecast_units" == "ca" ) {
                // ca = kph
                windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedKPH"];
                windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustKPH"];
            } else if ( "$Extras.forecast_units" == "si" ) {
                // si = meters per second. MPS is KPH / 3.6
                //windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedKPH"] / 3.6;
                //windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustKPH"] / 3.6;
                windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedKPH"];
                windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustKPH"];					
            } else {
                // us and uk2 and default = mph
                windSpeed = data[(forecast_interval)][0]["response"][0]["periods"][i]["windSpeedMPH"];
                windGust = data[(forecast_interval)][0]["response"][0]["periods"][i]["windGustMPH"];
            }

In the 1 hour forecast section of Belchertown.js.tmpl:

Comment out the line:
output_html += '<i class="wi wi-strong-wind"></i> <span>'+ parseFloat( forecast_row[i]["windSpeed"] ).toFixed(0) +'</span>';

Uncomment the line:
//  output_html += '<i class="wi wi-strong-wind"></i> <span>'+ parseFloat( forecast_row[i]["windSpeed"] ).toFixed(0) +'</span> | <span> '+ parseFloat( forecast_row[i]["windGust"] ).toFixed(0) +'$unit.label.windSpeed';

**Comment by fvirgola80** [comment]
good morning @ArendPWS, thank you very much for the suggestion, but I mean that the display of the wind on smartphones and tablets is shifted to the right as you can see in the figure, while from a PC it is perfect.
😉

**Comment by ArendPWS** [comment]
@fvirgola80 

Aha, now I understand. 🙂 I don't experience this behaviour on my smartphone. Did you already open an issue for this? Maybe that @poblabs or someone who is experiencing the same will come up with a solution. Below is a screenshot of my smartphone, this looks pretty normal/readable to me. So I have no idea what could be the issue with your smartphone.

Screenshot smartphone Belchertown

**Comment by fvirgola80** [comment]
@ArendPWS if you try to open the site http://lordshipweather.uk/hourly of @michaelundwd from a smartphone or tablet you will notice the same misalignment that I have too. I believe it is something in style.css
:-)

**Comment by ArendPWS** [comment]
@fvirgola80 

The only thing I can come up with right now is that a PR from @michaelundwd has been implented 11 days ago which made some CSS changes to the windrow class ( PR #444 ). I did not use this PR in my own skin version.

Maybe you can undo  the changes mentioned in his PR and see how this works out for you? Change/revert back to in style.css:

	.windrow {
		/* margin-top: 25px; */
		// box-sizing: border-box;
		border-top: 1px solid #D7D7D7;
		padding-top: 10px;
		// padding-right: 15px;
		/* margin: 0 -15px 0 -15px; */
		margin: 0 0 0 0;
		// width: 385px;
		width: 105%;		
	}

**Comment by fvirgola80** [comment]
Thanks a lot for the suggestion @ArendPWS now the visualization of the wind on smartphone and teblet is back correct, even from a PC you can see it well. We wait @michaelundwd for the changes to the files for the correct visualization of 1 and three hours on smartphones and tablets as in the test http://lordshipweather.uk/hourly.
:-)

**Comment by ChrisM510** [comment]
@michaelundwd  First, THANK YOU for sharing your work with us!

I implemented the changes, including the 2 files that were updated a couple days ago, and everything is working great, except for one minor spacing issue - the suffix on the time (AM/PM) is pushed down a line:

image

Any advice on what I should change to bring the AM/PM back up on the same line as the rest of the date/time stamp?

**Comment by fvirgola80** [comment]
I just edited the belchertown.js.tmpl and style.css files published by @michaelundwd and the result is fantastic.
If you go from a PC or from a smartphone or tablet, you can perfectly see the hourly and daily forecasts.
Great job @michaelundwd very good
www.meteocivitavecchia.it

**Comment by fvirgola80** [comment]
> @michaelundwd First, THANK YOU for sharing your work with us!
> 
> I implemented the changes, including the 2 files that were updated a couple days ago, and everything is working great, except for one minor spacing issue - the suffix on the time (AM/PM) is pushed down a line:
> 
> image
> 
> Any advice on what I should change to bring the AM/PM back up on the same line as the rest of the date/time stamp?

I have no display problems. Maybe because I have the 24H format in the system time?
Cattura

**Comment by ChrisM510** [comment]
> I have no display problems. Maybe because I have the 24H format in the system time?
> Cattura

I was thinking the same thing...  It is minor, and definitely something I can live with, if I have to.

**Comment by fvirgola80** [comment]
> > I have no display problems. Maybe because I have the 24H format in the system time?
> > Cattura
> 
> I was thinking the same thing... It is minor, and definitely something I can live with, if I have to.


Let's see others saying :-)

**Comment by michaelundwd** [comment]
@ChrisM510 
Thanks for this; it's because I used col-7 for the forecast-title and -5 for forecast-menu. -8 and -4 respectively fixes it.
I've updated the PR - commit 41ce9d8

@fvirgola80 
Take a look at my hourly test site again; I have modified what I did in #444 to give both alignment of temperature and wind (the original problem) **_and_** proper appearance on a phone.  Let me know if it's ok and I will update #444 accordingly.
Michael

**Comment by fvirgola80** [comment]
> @ChrisM510
> Thanks for this; it's because I used col-7 for the forecast-title and -5 for forecast-menu. -8 and -4 respectively fixes it.
> I've updated the PR - commit [41ce9d8](https://github.com/poblabs/weewx-belchertown/commit/41ce9d80bfc0513a225fd82cd7933bd6472cfece)
> 
> @fvirgola80
> Take a look at my hourly test site again; I have modified what I did in #444 to give both alignment of temperature and wind (the original problem) **_and_** proper appearance on a phone. Let me know if it's ok and I will update #444 accordingly.
> Michael
@michaelundwd
http://lordshipweather.uk/hourly/
I confirm that with the change you made in the index.html.tmpl file on smartphones and tablets, the wind display is now correct.
Good job
:-)

**Comment by ChrisM510** [comment]
@michaelundwd  I can confirm that those changes did the trick.  

Not sure if this is related to what you are working on with @fvirgola80 but I checked my mobile view, and the spacing for the wind speed / gust speed is pushed to the right, and the separator lines go all the way to the edge:

image

**Comment by fvirgola80** [comment]
> @michaelundwd I can confirm that those changes did the trick.
> 
> Not sure if this is related to what you are working on with @fvirgola80 but I checked my mobile view, and the spacing for the wind speed / gust speed is pushed to the right, and the separator lines go all the way to the edge:
> 
> image


In style.css it changes like this
.windrow {
	/* margin-top: 25px; */
	/* box-sizing: border-box; */
	border-top: 1px solid #D7D7D7;
	padding-top: 10px;
	/*padding-right: 15px; */
	/* margin: 0 -15px 0 -15px; */
	margin: 0 0 0 0;
	/*width: 385px; */
	width: 105%;		
}

**Comment by michaelundwd** [comment]
@ChrisM510 , @fvirgola80 
I have just created PR #459 to correct the windrow problems I created in #444.
The modifications are to index.html.tmpl and style.css, but as you are using PR #455, you will have to do the manual edits as #459 does not contain the forecast changes.  Let me know if you need more information.
Michael

**Comment by fvirgola80** [comment]
Good job :-)

**Comment by ChrisM510** [comment]
@michaelundwd Ok, I am thoroughly confused now...  I have no idea what you mean about #455 vs #459.  I made the changes that @fvirgola80 suggested above, which corrected my divider length and spacing issue, but now the divider between the temperature and the wind is gone entirely.  Can you just tell me what my final style.css file should look like?  :)

**Comment by michaelundwd** [comment]
@ChrisM510 
Apologies for the confusion - I am trying to keep the wind changes PR separate from the forecast changes PR.  This is what you need to do in two files.

index.html.tmpl:
~line 236 insert after `<!--` Wind -->

`<div` class="obs-wind-divider"></div>

style.css:
~line 863 insert following as a new element at end of @media only screen and (max-width: 1196px)

    .obs-wind-divider {
        display: none;    
    }

~line 1514 replace .windrow with

.obs-wind-divider {
    height: 1px;
    width: 105%;
    background-color: #D7D7D7;   
}

.windrow {
	/* margin-top: 25px; */
	/* box-sizing: border-box; */
	border-top: 1px solid #D7D7D7;
	padding-top: 10px;
	/* padding-right: 15px; */
	/* margin: 0 -15px 0 -15px; */
	margin: -1px  0 0 0;
	/* width: 105%;	*/	
}

Hope that works
Michael

**Comment by fvirgola80** [comment]
> @ChrisM510 
> Apologies for the confusion - I am trying to keep the wind changes PR separate from the forecast changes PR.  This is what you need to do in two files.
> 
> index.html.tmpl:
> ~line 236 insert after `<!--` Wind -->
> 
> `<div` class="obs-wind-divider"></div>
> 
> style.css:
> ~line 863 insert following as a new element at end of @media only screen and (max-width: 1196px)
> 
>     .obs-wind-divider {
>         display: none;    
>     }
> 
> ~line 1514 replace .windrow with
> 
> .obs-wind-divider {
>     height: 1px;
>     width: 105%;
>     background-color: #D7D7D7;   
> }
> 
> .windrow {
> 	/* margin-top: 25px; */
> 	/* box-sizing: border-box; */
> 	border-top: 1px solid #D7D7D7;
> 	padding-top: 10px;
> 	/* padding-right: 15px; */
> 	/* margin: 0 -15px 0 -15px; */
> 	margin: -1px  0 0 0;
> 	/* width: 105%;	*/	
> }
> 
> Hope that works
> Michael
> 
> 
> 
thanks @michaelundwd 😉😉

**Comment by ChrisM510** [comment]
@michaelundwd Ok, I was missing the change in index.html.tmpl but once I did it, everything went bonkers...I removed the line.  I suspect my file is now different from what you were expecting.  Here are a few lines from where you wanted me to insert that line.

`                        
                        <div class="row windrow">
                            <div class="weather-obs-bottom">
                            <div class="col-sm-12 current_wind">
                                <div class="col-sm-6">
                                    <div class="compass">
                                        <div class="direction">
                                            <span class="curwinddir">
                                            #if $current.windDir.ordinal_compass == "N/A"
                                            --
                                            #else
                                            $current.windDir.ordinal_compass
                                            #end if
                                            </span>
                                            <span class="curwinddeg">
                                            #if $current.windDir.raw is None:
                                            -
                                            #else
                                            $current.windDir.format("%.0f")
                                            #end if
                                            </span>
                                        </div>
                                        <div class="arrow"></div>
                                    </div>
                                </div>
                                <div class="col-sm-6 windspeedtable">
                                    <table class="wind-table">
                                        <tbody>
                                            <tr>
                                                <td class="windtext">$obs.label.wind_speed</td>
                                                <td class="windtext border-left gust">$obs.label.wind_gust</td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <span class="curwindspeed">
                                                        $current.windSpeed.toString(addLabel=False, NONE_string="--")
                                                    </span>
                                                </td>
                                                <td class="border-left gust">&nbsp;
                                                    <span class="curwindgust">
                                                        $current.windGust.toString(addLabel=False, NONE_string="--")
                                                    </span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="mph" colspan="3">$unit.label.windSpeed</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>`

**Comment by michaelundwd** [comment]
@ChrisM510 
I know the feeling; one little slip and away it goes!
Here is a zip file with the windrow mods incorporated into the latest forecast files.  You should be able to copy them across in entirety. 
If that does not work, try downloading the latest forecast from PR #455 again and then copying these files over. 
Michael
[#459.zip](https://github.com/poblabs/weewx-belchertown/files/5512907/459.zip)

**Comment by ChrisM510** [comment]
That did it!  Thank you so much!  I really appreciate you both helping me out!!!  :-D

**Comment by michaelundwd** [comment]
Great!

**Comment by ddperso** [comment]
@michaelundwd 
I have copied your files, all seems to be correct (thanks a lot for your work), except on the right part of forecast window only when I am on full screen on my pc (24 is shifted)
May be I have forgotten someting...
Do you have an idea? On your site, there is no problem...
image

**Comment by fvirgola80** [comment]
> @michaelundwd 
> I have copied your files, all seems to be correct (thanks a lot for your work), except on the right part of forecast window only when I am on full screen on my pc (24 is shifted)
> May be I have forgotten someting...
> Do you have an idea? On your site, there is no problem...
> image
> 

@ddperso tries to verify the change 41ce9d80bfc0513a225fd82cd7933bd6472cfece

**Comment by ddperso** [comment]
Thanks, it's work
The right values are : 
<div class="col-lg-7 forecast-title">
<div class="col-lg-5 forecast-menu">

**Comment by ddperso** [comment]
It's perfect!
On my Iphone SE, for 1 hour and 24 hours all is perfect, for 3 hours dates are not align, due to the forecast value in 2 lines (screenshot)
On my Ipad, no problem
On my PC no problem

image

**Comment by michaelundwd** [comment]
Thanks for the feedback @ddperso and the solution @fvirgola80 .  
There is a trade-off between the amount of space available for the forecast-title and the menu-caption, as both can be translated into text whose length I cannot predict.  I have since modified the amount of padding to maximise the amount of space for text in commit 3fb91e6
After that it is a matter of choosing the text to fit.
Michael

**Comment by ddperso** [comment]
Thanks, but no change...
image

**Comment by ddperso** [comment]
Hummm, for 1 hour, I have not the same presentation as you.
Temperature is not positionned just above precipitation %
Could you send me on a zip file the 3 files : .js, index and css (may be I have made a mistake...)
image

**Comment by michaelundwd** [comment]
Looks like you are not on the most recent version of the files as you only have two hours across the page and not four.  Here is the zip file you requested with .js, .index and .css from the latest commits on github. 
[ddperso_files.zip](https://github.com/poblabs/weewx-belchertown/files/5517001/ddperso_files.zip)

To fix your 3hour alignment problem, try changing the min-height **to** 90px **from** 80px ~ line 2281 in style.css
    .forecast-conditions {
        min-height: 90px;
    }
Michael

**Comment by ddperso** [comment]
Yes!!!
Perfect! with min-height: **90**px;
**Validate with PC, Iphone, Ipad for 1, 3 and 24 hours**
(I don't see on android mobile)

Great job Michael.

**Comment by michaelundwd** [comment]
Great! 
I have now incorporated that in the latest commit 395bd24
Thanks for your help
Michael

**Comment by michaelundwd** [comment]
I have had a look and cannot see anywhere in the changes that I made for the forecasts that would have affected the alerts.  I tried very hard to only change the things I had to; it was hard enough to do without making extra work!
Let's see if anyone else who has downloaded the forecast version is experiencing the same effect as you.  If so, I will certainly take a closer look.
Michael

**Comment by fvirgola80** [comment]
thank you very much @mochaelumdwd .... I do not question the great work you have done very well .... maybe aeres is not providing weather alerts right now ... I always think you did a great job ... 😉😉🔝🔝

**Comment by gand07** [comment]
Hi Michael

Thanks for this addition, it's great.
I have one question, is it by purpose that icons in 1-hour forecast are not aligned. Please see screenshot.

Thanks

Gert
Forecast

**Comment by michaelundwd** [comment]
@fvirgola80 
No problem - I'm grateful for your help in debugging it.  I suggest the lack of an an alert is exactly that as I don't see any alerts in the UK unless they have been produced by the UK Met Office and then picked up by Aeris.  See https://www.aerisweather.com/support/docs/api/reference/endpoints/alerts/ for more details.

@gand07 
If you mean for the different temperatures, yes, this is by design.  As there was no space for  the conditions-text in the narrower cells for the 1 hour forecast, and I wanted to maintain the same height as the other forecasts, I decided to use the vertical space to provide a graphical representation of the temperature throughout the day, just like the BBC weather site for London https://www.bbc.co.uk/weather/2643743.  The temperatures are aligned for narrower screens when there are 4 readings per row where maintaining the same height is less important.

However, if you mean the first two 10°C readings on your screenshot are not aligned, that is because of the way the wind is displayed.  Try removing the m/s from the belchertown.js.tmpl and see if that fixes it.  What screen width were you using for the screenshot?  Have you changed the widths for the forecasts accordingly?

Michael

**Comment by fvirgola80** [comment]
> @fvirgola80
> No problem - I'm grateful for your help in debugging it. I suggest the lack of an an alert is exactly that as I don't see any alerts in the UK unless they have been produced by the UK Met Office and then picked up by Aeris. See https://www.aerisweather.com/support/docs/api/reference/endpoints/alerts/ for more details.
> 
> @gand07
> If you mean for the different temperatures, yes, this is by design. As there was no space for the conditions-text in the narrower cells for the 1 hour forecast, and I wanted to maintain the same height as the other forecasts, I decided to use the vertical space to provide a graphical representation of the temperature throughout the day, just like the BBC weather site for London https://www.bbc.co.uk/weather/2643743. The temperatures are aligned for narrower screens when there are 4 readings per row where maintaining the same height is less important.
> 
> However, if you mean the first two 10°C readings on your screenshot are not aligned, that is because of the way the wind is displayed. Try removing the m/s from the belchertown.js.tmpl and see if that fixes it. What screen width were you using for the screenshot? Have you changed the widths for the forecasts accordingly?
> 
> Michael

@michaelundwd 
I tried to debug actually known that there are errors in the alerts I am attaching image
debug

**Comment by michaelundwd** [comment]
@fvirgola80 
I took a look at your site and also tried putting Civitavecchia directly into the Aeris alert wizard and got the same result.  So Aeris is saying it is a valid request but there are no alerts. I don't think its a skin problem.
Try raising the issue with the Aeris Support desk if you have not done so already.  I have found them very helpful in resolving the issues I have had. 
Michael

**Comment by fvirgola80** [comment]
@michaelundwd 
I also performed the procedure and instead of entering Civitavecchia I entered Lazio, IT and it worked. In your opinion where should I sistmare Lazio instead of Civitavecchia?

**Comment by fvirgola80** [comment]
Could it depend on the coordinates in weewx.conf?

**Comment by michaelundwd** [comment]
Yes it could
However, the response from Lazio is saying no report, but the one from Civitavecchia is saying there is not a report.
I will reply directly to your email address
Michael

**Comment by fvirgola80** [comment]
thanks Michael I'll rewrite my email address fvirgola80@gmail.com thanks

**Comment by fvirgola80** [comment]
good morning Michael how are you? ... I wanted to ask you something ... If you go to my site and select the 1 hour and 3 hour times you will notice that the weather icons are not present why? thanks a lot😉

**Comment by michaelundwd** [comment]
Good afternoon Francis
Yes, I had discovered that when I checked your site yesterday as I have lost the alerts on mine, but they are showing on yours, so that problem is my set up.

There are 5 missing icons are for the weather condition Pioggia, so I have downloaded data for your co-ordinates (42.09, 11.80) to see why you are getting an “undefined” for the icon.

It is not clear from the data why five of the readings, 17:00 – 21:00 hrs are showing the undefined.png icon.  It will take some time to investigate, so will reply when I have an answer for you.

Michael

**Comment by fvirgola80** [comment]
Thanks a lot Michael😉

**Comment by fvirgola80** [comment]
Hello Michael ... have you seen the Added AQI from Aerisweather # 475 .. second how can we integrate it into your previous modification with the hourly forecast?

**Comment by fvirgola80** [comment]
You could answer me by email I lost your address :-)

**Comment by michaelundwd** [comment]
Francis
Yes, I have seen this, but have not been following closely as I have been unwell recently.  I agree it looks good but merging it into the forecast mods is not trivial.  I will NOT be doing it until the forecast PR is merged into the master.  The right way to proceed is for the Belchertown owner (Pat)  to do the merges of all the pull requests in turn, rather than adding modifications on top of unmerged modifications.  I made changes in 5 files, some of them very significant.

You can take the risk and do it yourself, but your problem is that the AQI mods will be working from the original master base and not the “forecast “PR, so how will you know which mods are which?

My advice is to wait until Pat has time to do the merges, or you could decide to scrap the forecast mods and adopt the AQI ones instead.

I have changed the title of this email to AQI and suggest you don’t lose my email again – how did that happen?

Apologies for not responding to your missing icon problem.  From the analysis I have done, it is not obvious and I have not been well enough the past few days to look into it further – apologies.

Michael

**Comment by fvirgola80** [comment]
Thank you so much for your reply Michael and I'm sorry if you haven't been well in this period 😔 .... ok I follow your advice .... you're right .... I accidentally deleted your email address so you I wrote in github .... when you have time send me an email so I'll write you there. Thanks a lot as always 😉

**Comment by ChrisM510** [comment]
Hi guys....ran into an issue this morning.  I updated the software on my Pi (using Webmin) and rebooted, and now I have lost my forecast data.  I ran sudo wee_reports, and also waited until almost an hour had passed to see if it would download at a specific interval...no luck.  Any ideas?

image

**Comment by michaelundwd** [comment]
It's the forecast file not downloading at hourly intervals, which after a couple of hours will synchronise to the hour.  Try the following if it has not cured itself.
Delete the forecast.json file  in the /forecast folder, and it should refresh at the next archive interval, then at the next hour.
Then try restarting weewx if that fails.
Michael

**Comment by ChrisM510** [comment]
Well, I did as you recommended, but no luck.  Aeris is definitely being pinged - I have a hit count today when I log into their main page.  My forecast.json file appears to have an error in it...

{"timestamp": 1608208229, "alerts": [{"response": [], "success": true, "error": {"code": "warn_no_data", "description": "Valid request. No results available based on your query parameters."}}]

[forecast.zip](https://github.com/poblabs/weewx-belchertown/files/5709366/forecast.zip)

Ideas?  So weird that it was working fine before I rebooted after the updates (and none of the updates were to WeeWX or Belchertown).

**Comment by ChrisM510** [comment]
Looks like @poblabs  himself was having a similar issue about 3 weeks ago...

https://obrienlabs.net/belchertownweather-com-website-theme-for-weewx/

**Comment by michaelundwd** [comment]
No alerts is not an issue if there were none.
There is valid data in the file, but it won’t format as json data in notepad++
Unlikely aeris have done anything as it is only since you updated your Pi.
Can only suggest it is something that weewx/Belchertown depends on that has done it.
What were the changes in the update?
I’m not an expert on Pi, so try asking around.
Big ask this, but can you undo the Pi update?
In haste
Michael

**Comment by ChrisM510** [comment]
Hi Michael!  Thanks (again) for your help...out of nowhere, it appears to be working again.  Maybe I just wasn't patient enough (more than likely).  :-)

**Comment by michaelundwd** [comment]
Great.  Let’s hope it stays that way. Not sure why a delay would fix it, but I’m really pleased as I didn’t have a clue as to how to fix it!
Michael

**Comment by ChrisM510** [comment]
Well, it's acting up again...that almost certainly means it has to be an issue with Aeris, because I haven't touched it since my last message on here.  :-)

**Comment by michaelundwd** [comment]
It might be worth raising an Aeris support ticket to see if they have changed anything, although I have not had any problems.  Something peculiar to your location maybe?

The only thought I have is whether the time and date on your Pi is running correctly, but that would not explain how there was data there in what looked like the wrong format.

It’s worth keeping a note of the forecast times when it does work, to see if there is any pattern in the timing.  Might take a few days to spot that.

Michael

**Comment by ChrisM510** [comment]
Ticket opened...they want to know what query I am submitting.  How do I find that out?  :-)

**Comment by michaelundwd** [comment]
I should have remembered Aeris would ask for that.  At the end are the 3 forecast calls for my weather station.

However, I would start by looking locally first, as your update was the trigger for all this.  As it works occasionally, I would check the system clock/time on your Pi.  Is it being updated regularly?  If for example, it was only updated once per day, you would only get one set of forecasts in a 24 hour period.

To check how many requests Aeris is getting daily from your Pi, log in to your Aeris account and see how many requests it has had in the day.  Normally, there are 5 every hour from the skin, and the number is reset at midnight.

Next look at the time on your forecast.json file. Does that change at hourly intervals?

Then I suggest you try using the api calls below to see if they will return data for you in your browser.  If they do, the issue is NOT Aeris, but your Pi.

Replace <lat> and <long> with your coordinates, likewise <id> and <secret> in the calls below.  Do not include the < >  in what you submit.

For example, the first part of my calls is https://api.aerisapi.com/forecasts/51.97,-0.22?

24 hour Forecast Call
==================
https://api.aerisapi.com/forecasts/<lat>,<long>?&format=json&filter=day&limit=7&client_id=<id>&client_secret=<secret>

3 Hour Forecast Call
====================

https://api.aerisapi.com/forecasts/<lat>,<long>?&format=json&filter=3hr&limit=8&client_id=<id>&client_secret=<secret>

1 Hour Forecast Call
====================

https://api.aerisapi.com/forecasts/<lat>,<long>?&format=json&filter=1hr&limit=16&client_id=<id>&client_secret=<secret>

Michael

**Comment by michaelundwd** [comment]
Pat
I have resolved the conflicts between 1.2_forecast and master and committed the changes using the conflict resolve editor in github.  I could see no way of issuing those other than using github.exe to pull the modified files to my computer and then issuing a PR with the changes to all the files!.  Having done that I can see no sign of it having been issued.  Are you able to find it?
There were changes to belchertown.py and belchertown.js.tmpl only.
As you can see I am still having issues as a github newbie!
Thanks Michael

**Comment by James-76** [comment]
@michaelundwd, before it is merged you have a typo in your belchertown.py on lines 993 and 1024 with your second quote in the wrong place.

```
                                                                        [json.loads(forecast_24hr_page)],
                                                                        "forecast"_3hr:
                                                                        [json.loads(forecast_3hr_page)],
```

James

**Comment by michaelundwd** [comment]
Thank you James.  I think the merge will have to be done by Pat @poblabs, but I have made the changes and committed them.
Thanks for spotting this.
Michael

**Comment by James-76** [comment]
No worries.  I did a pull of your setup and installed it on mine and everything seems to be working along side the AQI changes that have already been committed.

**Comment by michaelundwd** [comment]
Thanks James for checking that the revised commit is available and works with the  AQI changes.  I have no easy way of checking it out as I have deliberately made no more changes until Pat had merged it.
Michael

**Comment by poblabs** [comment]
Sorry everyone, have been a bit disconnected lately. Looks like there's been some good progress here. I'll merge it in!

**Pull request merged**
