### PR TITLE
Added gauge chart option

### PR DESCRIPTION
**Pull request by uajqq**
Building off the AQI Chart option, this is a general gauge-style chart that can be used to show any data point, not just AQI. Good for showing values on a set scale (e.g. humidity).  **This pull request also changes the style of the Aeris AQI gauge to match.**

### How to use:
The simplest configuration will give a gauge chart from 0-100 with the specified value:
```
[[exampleGauge]]
    title = Example gauge chart
    type = gauge
    [[[outTemp]]]
```
D8B875B4-14AF-4DC1-B7CC-FCC3388A80AF

Users can specify rounded edges if they wish, and also change the color:
```
    [[exampleGauge]]
        title = Example gauge chart
        type = gauge
        [[[outTemp]]]
            rounded = 1
            color = "#f7a35c"
```
F6457958-CF52-49CE-B949-C66648349552

However, users can also specify a list of threshold colors, so the gauge will change colors dynamically depending on the value being graphed. Enable by setting `colors_enabled = 1`. 

Users can set up to 7 colors. Both the color and the color position must be set. When the value rises above a particular color position, the corresponding color will be set. For example, wind gust speed can be color-coded as follows (note the y-axis max and min have been manually set to better match a range of possible wind speeds). In this example, the wind speed has just increased above `color4_position`, so `color4` is the one that gets set:
```
    [[exampleGauge]]
        title = Example gauge chart
        type = gauge
        [[[windGust]]]                                                                                                                        
                rounded = 1      
                colors_enabled = 1                                                                                                                
                color1_position = 3                                                                                                              
                color1 = "#1278c8"                                                                                                               
                color2_position = 7                                                                                                              
                color2 = "#1fafdd"                                                                                                               
                color3_position = 12                                                                                                             
                color3 = "#71bc3c"                                                                                                               
                color4_position = 20                                                                                                             
                color4 = "#ffae00"                                                                                                               
                color5_position = 30                                                                                                             
                color5 = "#ff7f00"                                                                                                               
                color6_position = 40                                                                                                             
                color6 = "#ff4500"                                                                                                               
                color7_position = 50                                                                                                             
                color7 = "#9f00c5"
                yAxis_min = 0
                yAxis_max = 70
```
B20AA7AF-89F1-4838-BAC1-A7223940572A

Users can use the built-in Belchertown aggregation functions to graph maximums, averages, etc. For example, setting `time_length = 2629800 `, `aggregate_interval = 2629800` (1 month in seconds), and `aggregate_type = min` gets us the minimum temperature for the past month:
07B3AEFC-17B4-46C6-8661-1F805074BE0F

Maximum wind speed over the past 24 hours (`time_length = 86400`, `aggregate_interval = 86400`, `aggregate_type = max`):
6F1B90B3-A452-4CDB-BE8D-4538B0241DA8

You can of course set fewer than 7 colors—for example, just red/green. For example, I set my signal strength indicator on a scale from 90-100%. Green as long as it’s above 98%, red below that.

I was having a decimal point issue that was fixed very nicely by #491–thank you!!

### CODE REVIEW

**Comment by poblabs** [comment]
Awesome, thanks! Don't forget to update the charts wiki if you haven't done so!

**Comment by Distortionist** [comment]
Quick question about the chart....

I have a plugin that calculates AQI based on whatever information I can give it. Anyway, when I chart its values it works but shows undefined underneath it. I tried name = AQI but it did not work, I have included a picture.  I guess the "units" are not stored in its database. Is there a way to get rid of the undefined, or give it a name?

image

**Comment by uajqq** [comment]
Try setting units for AQI to "" in your weewx.conf?

**Comment by Distortionist** [comment]
I am not sure i know how. I tried under Labels, but it didn't do anything.
I am not sure how weewx ties database entries to their acronyms. I don't
see them in the configuration file. I was hoping I could add a line like
name = blah in the graphs section. Or tell it to not include it all.

**Comment by uajqq** [comment]
For the AQI graph, are you using an instance of [[aqiChart]], or are you graphing AQI using a gauge chart?

**Comment by Distortionist** [comment]
I am graphing aqi using the Guage chart from my own pm 2.5 readings, and a
weewx extension that converts it to AQI and puts it in a separate database.
I have to define the database binding on the chart.

 It works just got a line saying undefined under the reading. Would you
like to see the charts entry? I honestly don't think it has anything to do
with Belchertown. Weewx just doesn't know the units or its not stored in
the database or something. I was just hoping there was a line I can add to
override it or remove the unit.

**Comment by 41south** [comment]
I've been experimenting with AQI data for a while, but I store it in the
Weewx database after extending the schema. My results are here;

http://41south.nz/graphs/?graph=AQM

I can't the gauge style to work at all at the moment but when I do I'll see
how the AQI data looks

Colin

**Comment by uajqq** [comment]
> I was just hoping there was a line I can add to
> override it or remove the unit.

Try setting:
```
[StdReport]
    [[Defaults]]
        [[[Units]]]
            [[[[Labels]]]]
                aqi = ""
```

Assuming the custom observation you're graphing is called `aqi`.

**Comment by Distortionist** [comment]
I just tried, and it did not work. The actual observation is called aqi_pm2_5, but I tried both aqi and that  = "" and they did not work, but I did notice the guage acting up! When I click on graphs in belchertown, the PM 2.5 reading starts showing undefined. I don't think it is related, but it certainly is odd! Try it, visit my page at http://livingstonecove.ca you will see 2 of these new guages there, the calculated AQI by the weewx-aqi plugin,  which shows undefined, and the PM 2.5 reading from my sensor, which shows ug/m3 underneath. If I click on Graphs to view all the graphs, they both show up like they should but this time the PM 2.5 graph shows undefined instead of ug/m3 lol.  I can't win!

Here is what the relevant section of my configuration looks like :
<code>
[homepage]
    # Chart Timespan Defaults
    title = "Today's Conditions"
    show_button = true
    button_text = "Homepage"
    time_length = today
    tooltip_date_format = "LLL"
    gapsize = 300 # This should be your archive_interval from weewx.conf

        [[chart1]]
        title = AQI
        type = gauge
        data_binding = aqi_binding
                [[[aqi_pm2_5]]]
                        rounded = 0
                        colors_enabled = 1
                        color1_position = 51
                        color1 = "#71bc3c" # Good
                        color2_position = 101
                        color2 =  "rgba(255,174,0,0.9)" # Moderate
                        color3_position = 151
                        color3 = "rgba(255,127,0,1)" # Unhealthy for sensitive groups
                        color4_position = 201
                        color4 = "rgba(255,69,69,1)"  # Unhealthy
                        color5_position = 301
                        color5 = "#b16286" # Very unhealthy
                        color6_position = 500
                        color6 = "#cc241d"  # Hazardous
                        yAxis_min = 0
                        yAxis_max = 500

        [[chart2]]
        title = PM 2.5
        type = gauge
                [[[pm2_5]]]
                        rounded = 0
                        colors_enabled = 1
                        color1_position = 12.1
                        color1 = "#71bc3c" # Good
                        color2_position = 35.4
                        color2 =  "rgba(255,174,0,0.9)" # Moderate
                        color3_position = 55.4
                        color3 = "rgba(255,127,0,1)" # Unhealthy for sensitive groups
                        color4_position = 150.4
                        color4 = "rgba(255,69,69,1)"  # Unhealthy
                        color5_position = 250.4
                        color5 = "#b16286" # Very unhealthy
                        color6_position = 350.4
                        color6 = "#cc241d"  # Hazardous
                        yAxis_min = 0
                        yAxis_max = 500
</code>

**Comment by Distortionist** [comment]
I am not sure where I should mention this anymore, sorry if this is the wrong place or should start a new issue, but I tried your option for aqi_location_enabled = 1, and I get no location under it.  I was curious what it looked like when I tried it. Sorry if I am making you pull your hair out. Merry Christmas and Happy new year. I do love what you have done and I obviously use all of it.

**Comment by uajqq** [comment]
> If I click on Graphs to view all the graphs, they both show up like they should but this time the PM 2.5 graph shows undefined instead of ug/m3

Not sure why these would be different. Keep in mind the graphs are refreshed on different schedules--is it possible those just haven't updated yet with your changes? You can force them by running `wee_report`.

With regard to the label issue, since the observation is `aqi_pm2_5`, that's the label you'd need to change. You said you'd tried setting the following in weewx.conf?
```
[StdReport]
    [[Defaults]]
        [[[Units]]]
            [[[[Labels]]]]
                aqi_pm2_5: ""
```

If that's not working, I would check around the weewx documentation to see how to set the label for a custom observation. Since you're using a custom driver, it's hard to diagnose the issue--the label may need to be set at the level of your Python driver.

In the meantime, I just pushed a commit to my aqi branch that should make the label show as blank if nothing is defined, instead of "undefined." I can't test it myself. Does it make a difference?

**Comment by uajqq** [comment]
> I am not sure where I should mention this anymore, sorry if this is the wrong place or should start a new issue, but I tried your option for aqi_location_enabled = 1, and I get no location under it.

Is the option set in weewx.conf like this? Make sure it's in the Extras stanza.
```
[StdReport]
    [[Belchertown]]
        [[[Extras]]]
           aqi_location_enabled = 1
```

**Comment by Distortionist** [comment]
Yes it was! It could be that I had to wait for the next time it updated its
forecast from aeries and I did not wait long enough. I will try it again
after work.

**Comment by Distortionist** [comment]
> If that's not working, I would check around the weewx documentation to see how to set the label for a custom observation. Since you're using a custom driver, it's hard to diagnose the issue--the label may need to be set at the level of your Python driver.
> 
> In the meantime, I just pushed a commit to my aqi branch that should make the label show as blank if nothing is defined, instead of "undefined." I can't test it myself. Does it make a difference?

Yeah it is weird, because I only define each chart once, so it is the exact same gauge lol. I need to learn how to program so I am less of a burden and more helpful here. That being said showing nothing rather than "undefined" is a perfect solution for me. Thank you.

You should look at the weewx-aqi extension, the guy is not answering but I think he built something cool there that you guys can work with. It can calculate a bunch of different air quality standards, and it has their equivalent label and color all accessible through the database. It is way beyond my skill level making proper use of it with Belchertown.

**Comment by Distortionist** [comment]
Another weird thing. I can see your graphs working in the example pictures, but on my AQI gauge it did not change when I thought it should. The configuration is posted a couple posts up, but today the AQI hit 53, and did not change from green. I took a snapshot at 52, which also should have been changed from green. Sometimes I think my raspberry pi is messing with me on purpose. Could it be some weird entry in their aqi database that makes it think the values are not numbers or something? I am stumped again, not that it is hard to stump my newbness. 

image

**Comment by Distortionist** [comment]
My bad, I guess some changes did happen. Here is another screen shot. I guess I just need to adjust the colors, but the text is kinda weird, it is not consistent. Here is a new screenshot when the numbers dropped :
image

**Comment by Distortionist** [comment]
Ok I invistaged this further. The colors when I look them up on the browser don't match what is produced in belchertown at all. I have a dark mode plugin that was not set to turn on for my weather site, so I disabled it, but it did not change anything. I tried turning off dark theme in Edge, and that did not help it either. I turned off dark theme in belchertown, and that did not help it either! I tried in chrome, and that did not change anything as well.

Here is a new screenshot of when one value dipped to color 1 and the other is in color 2. you can see the difference in color, the color is 100% wrong when I lookup their codes online in the same browser with the same plugins. Also you can see why one side the text is goes black for color one, and the text is green and matches color 2, although it is displayed in green instead of orange lol.

What the heck is going on here? This is odd right? I just installed this version of Belchertown as well when your charts got merged into main so I don't think it is something I did here. The AQI chart is pulled from an aqi.sdb and the PM 2.5 is pulled from weewx.sdb so it is not something weird in aqi.sdb. It is either my weewx, or my belchertown I guess?

image

**Comment by Distortionist** [comment]
At least some colors are displaying correctly, this has nothing to do with your charts, this is the Seasons theme with what I did in there for AQI just testing and playing. It seems to do colors properly, although they are produced completely differently. It seems the chart generator is what is screwing up the colors.

image

**Comment by uajqq** [comment]
I’m at a loss. It might be best to completely reinstall from scratch at this point—it seems like some configuration setting is broken somewhere.

**Comment by Distortionist** [comment]
> I’m at a loss. It might be best to completely reinstall from scratch at this point—it seems like some configuration setting is broken somewhere.

Yeah I thought this was kinda odd, I went and upgraded EVERYTHING in my pi but it did not help. I added "" to anything odd in the config files so weird characters are not screwing things up.. nothing worked.. but I fixed it!!!

I fixed it by adding another color line I think. I will wait to see if AQ spikes again. It looks like it is using whatever color it wants for the first part, so I added a new color1_position = 0, and I left the rest exactly the same other than shifting the numbers over a digit. It  shows the right green but I doubt it will shift to orange at 51 without me having position 2 starting at 51 in the AQI chart for example. 

Here is what I got now anyway. Colors look much better and no black text. If it stays green when it goes over 50, I will just have to move the color codes up the list.

 
image


Here is what I did with the config incase I can't explain myself properly.

<code>

        [[chart1]]
        title = AQI
        type = gauge
        data_binding = aqi_binding
                [[[aqi_pm2_5]]]
                        rounded = 0
                        colors_enabled = 1
                        color1_position = 0
                        color1 = "#71bc3c" # Good
                        color2_position = 51
                        color2 = "#71bc3c" # Good
                        color3_position = 101
                        color3 =  "#ffae00" # Moderate
                        color4_position = 151
                        color4 = "#ff7f00" # Unhealthy for sensitive groups
                        color5_position = 201
                        color5 = "#ff4545"  # Unhealthy
                        color6_position = 301
                        color7 = "#b16286" # Very unhealthy
                        color8_position = 500
                        color8 = "#cc241d"  # Hazardous
                        yAxis_min = 0
                        yAxis_max = 500

        [[chart2]]
        title = PM 2.5
        type = gauge
                [[[pm2_5]]]
                        rounded = 0
                        colors_enabled = 1
                        color1_position = 0
                        color1 = "#71bc3c" # Good
                        color2_position = 12.1
                        color2 = "#71bc3c" # Good
                        color3_position = 35.4
                        color3 =  "rgba(255,174,0,0.9)" # Moderate
                        color4_position = 55.4
                        color4 = "rgba(255,127,0,1)" # Unhealthy for sensitive groups
                        color5_position = 150.4
                        color5 = "rgba(255,69,69,1)"  # Unhealthy
                        color6_position = 250.4
                        color6 = "#b16286" # Very unhealthy
                        color7_position = 350.4
                        color7 = "#cc241d"  # Hazardous
                        yAxis_min = 0
                        yAxis_max = 500
</code>

**Comment by Distortionist** [comment]
Would be awful nice if it supports color1_label=    :)

**Comment by uajqq** [comment]
I see what the problem is. I incorporated a fix for this bug a while ago but somehow it didn’t make it into the commit. I didn’t even think to check because I was certain I had fixed this exact bug earlier. Install the latest version from my AQI branch and this config should work for AQI (and remove the “undefined” label):
```
    [[chart1]]
    title = AQI
    type = gauge
    data_binding = aqi_binding
            [[[aqi_pm2_5]]]
                    rounded = 0
                    colors_enabled = 1
                    color1_position = 51
                    color1 = "#71bc3c" # Good
                    color2_position = 101
                    color2 =  "rgba(255,174,0,0.9)" # Moderate
                    color3_position = 151
                    color3 = "rgba(255,127,0,1)" # Unhealthy for sensitive groups
                    color4_position = 201
                    color4 = "rgba(255,69,69,1)"  # Unhealthy
                    color5_position = 301
                    color5 = "#b16286" # Very unhealthy
                    color6_position = 500
                    color6 = "#cc241d"  # Hazardous
                    yAxis_min = 0
                    yAxis_max = 500
```

**Comment by Distortionist** [comment]
Awesome thank you. I still think in the chart color1_position should be actually 0, and color2_position should start at 51, from what I am seeing here. Ill know when AQI spikes again, maybe ill go smoke a beside it. It is not something you need to fix anywhere, its not in the documentation, it was just an sample config you made for me I think.

I now don't see the undefined anymore, thanks it is much better without it, although one small weird consequence is formatting changed a bit. It is not an issue but I am sure it would look much better and calm down OCD people if it was fixed.  Here is what I mean, look at the new position of the AQI number in the gauge. It just looks funny beside the other one, I don't think anyone would care if it was alone.

image

**Comment by uajqq** [comment]
See if it looks better on the latest version.

**Comment by uajqq** [comment]
> Awesome thank you. I still think in the chart color1_position should be actually 0, and color2_position should start at 51, from what I am seeing here.

Yes, sorry, copied wrong thing--edited to fix

**Comment by Distortionist** [comment]
It looks much better! Thank you very much. What are the chances you can make it support custom labels per color too? So I can actually set the name of the condition for people, for example color1_label = Good   and color2_label = Moderate ?

That would make your gauge absolutely perfect! It would be the final touch in your work of art :)

image

**Comment by uajqq** [comment]
Give the latest version a try--set color1_label, color2_label, etc.

**Comment by Distortionist** [comment]
> Give the latest version a try--set color1_label, color2_label, etc.

I love you! It works great! It is beautiful! You are awesome :) Thank you very much, I really appreciate all your troubles.

image

**Pull request merged**
