### PR TITLE
Add option to display gust beaufort category

### PR DESCRIPTION
**Pull request by uajqq**
Adds `beaufort_category_gusts` option to make Beaufort category refer to wind gusts instead of current wind speed.

### CODE REVIEW

**Comment by fvirgola80** [comment]
hello, waiting for the integration in the master to try it ... great job @uajqq 🔝

**Comment by fvirgola80** [comment]
I thought it would be interesting to add the information on the type of wind according to the wind rose (tramontana, sirocco etc.) used in the Mediterranean and then add the value in knots close to the wind speed and the gust. it can be done? @uajqq

**Comment by uajqq** [comment]
That might be difficult--as I understand it, a tramontana is a specific kind of north wind, for example, not just any wind from the north. Could you chance the cardinal direction labels in skin.conf or weewx.conf to suit your purpose?

**Comment by fvirgola80** [comment]
exact is one of the types of winds look here https://it.m.wikipedia.org/wiki/Rosa_dei_venti .... I could follow your advice in configuring skin.conf or weewx.conf ... but the question is where? ... regarding the request to be able to also enter the wind value in knots in addition to km?

**Comment by fvirgola80** [comment]
you say these?
[[Ordinates]] # The ordinal directions. The last one should be for no wind direction directions = N, NNE, NE, ENE, E, ESE, SE, SSE, S, SSW, SW, WSW, W, WNW, NW, NNW, N/A

**Comment by fvirgola80** [comment]
Here it should look like in figure 1 in figure 2 I have entered the table of winds and in figure 3 all types of winds and direction
obviously it must be adapted to display on PCs and smartphones
Cattura

**Comment by fvirgola80** [comment]
You could think of moving more on Speed ​​and gust km / h and the beaufort and insert under the type of wind and as shown in the image insert the values ​​in knots
Cattura

**Comment by fvirgola80** [comment]
hello @uajqq I managed to get the result I wanted, I changed the skin.conf file in the line
`  [[Ordinates]]
        # The ordinal directions. The last one should be for no wind direction
        directions = N Tramontana , NNE Grecale , NE Gracale, ENE Levante, E Levante, ESE Scirocco , SE Scirocco, SSE Scirocco, Ostro S, SSW Libeccio, SW Libeccio, WSW Ponente, W Ponente, WNW Maestrale, NW Maestrale, NNW Maestrale, N/A`

and I also changed the style.css file to the line
`.direction .curwinddir {
    font-size: 17px;
    padding-top: 19px;
    display: block;
}
`
obtaining this result
Cattura

would it be possible to insert it in the master?
As far as concerns the request to enter the values ​​also in wind knots it is feasible.
Thank you

**Comment by areax99** [comment]
> hello @uajqq I managed to get the result I wanted, I changed the skin.conf file in the line
> ` [[Ordinates]] # The ordinal directions. The last one should be for no wind direction directions = N Tramontana , NNE Grecale , NE Gracale, ENE Levante, E Levante, ESE Scirocco , SE Scirocco, SSE Scirocco, Ostro S, SSW Libeccio, SW Libeccio, WSW Ponente, W Ponente, WNW Maestrale, NW Maestrale, NNW Maestrale, N/A`
> 
> and I also changed the style.css file to the line
> `.direction .curwinddir { font-size: 17px; padding-top: 19px; display: block; } `
> obtaining this result
> Cattura
> 
> would it be possible to insert it in the master?
> As far as concerns the request to enter the values ​​also in wind knots it is feasible.
> Thank you

Good

**Comment by dtalens** [comment]
> hello @uajqq I managed to get the result I wanted, I changed the skin.conf file in the line
> ` [[Ordinates]] # The ordinal directions. The last one should be for no wind direction directions = N Tramontana , NNE Grecale , NE Gracale, ENE Levante, E Levante, ESE Scirocco , SE Scirocco, SSE Scirocco, Ostro S, SSW Libeccio, SW Libeccio, WSW Ponente, W Ponente, WNW Maestrale, NW Maestrale, NNW Maestrale, N/A`
> 
> and I also changed the style.css file to the line
> `.direction .curwinddir { font-size: 17px; padding-top: 19px; display: block; } `
> obtaining this result
> Cattura
> 
> would it be possible to insert it in the master?
> As far as concerns the request to enter the values ​​also in wind knots it is feasible.
> Thank you

I added the names of the winds but it shows nothing, only cardinal points. I also added the style changes to custom.css and it has actually gotten smaller.

**Pull request closed without merging**
