### PR TITLE
Aeris cloud cover option

### PR DESCRIPTION
**Pull request by uajqq**
Adds the option to display cloud cover (in percentage) from Aeris Weather in the station observations section.

FC32AB36-C477-47B0-A829-2E96FE39CB1A

### CODE REVIEW

**Comment by fvirgola80** [comment]
Thank you so much for the information I tried to enter the clod_cover information but it says "invalid observation" I inserted the variable first in the Extra observation labeLs section but it returns the error then in station observation table and I have the same error. Do I need to change anything in the weewx.conf? how did I do for the Beaufort?

**Comment by uajqq** [comment]
Try setting `station_observations = cloud_cover, (...)` in weewx.conf. See the readme for details. Also make sure you have Aeris weather activated and working correctly.

**Comment by fvirgola80** [comment]
gave me this error

**Comment by fvirgola80** [comment]
on the site it works but it gives me the error I attached to you

**Comment by uajqq** [comment]
The error is because when you replaced belchertown.py with this version, you lost the updates that were fixed as part of the Python 2 bugs. The two fixes are on separate branches and haven’t been merged together yet. Therefore, cloud_cover works but Python 2 is having problems again. Until everything is merged, you’ll have to choose between Python 2 errors or cloud_cover. Unless you update to Python 3, that is...

**Comment by fvirgola80** [comment]
> The error is because when you replaced belchertown.py with this version, you lost the updates that were fixed as part of the Python 2 bugs. The two fixes are on separate branches and haven’t been merged together yet. Therefore, cloud_cover works but Python 2 is having problems again. Until everything is merged, you’ll have to choose between Python 2 errors or cloud_cover. Unless you update to Python 3, that is...


Ok for the moment I leave it so when there will be the correction for python2 and the two branches will be hooked I will replace the file.
Let's see how it goes

**Comment by fvirgola80** [comment]
> > The error is because when you replaced belchertown.py with this version, you lost the updates that were fixed as part of the Python 2 bugs. The two fixes are on separate branches and haven’t been merged together yet. Therefore, cloud_cover works but Python 2 is having problems again. Until everything is merged, you’ll have to choose between Python 2 errors or cloud_cover. Unless you update to Python 3, that is...
> 
> Ok for the moment I leave it so when there will be the correction for python2 and the two branches will be hooked I will replace the file.
> Let's see how it goes

I attach syslog
[syslog.zip](https://github.com/poblabs/weewx-belchertown/files/5868101/syslog.zip)

**Comment by fvirgola80** [comment]
I noticed that after the last belchertown.py no more information about earthquakes appears
Cattura

**Comment by fvirgola80** [comment]
> The error is because when you replaced belchertown.py with this version, you lost the updates that were fixed as part of the Python 2 bugs. The two fixes are on separate branches and haven’t been merged together yet. Therefore, cloud_cover works but Python 2 is having problems again. Until everything is merged, you’ll have to choose between Python 2 errors or cloud_cover. Unless you update to Python 3, that is...

what version of python3 should i install?

**Comment by uajqq** [comment]
Whatever the latest version is--3.6 or higher is a good idea

**Comment by fvirgola80** [comment]
> Whatever the latest version is--3.6 or higher is a good idea

is 3.8 okay?

**Comment by uajqq** [comment]
Yes

**Comment by fvirgola80** [comment]
> Yes

ok 

thanks. I hope the belchertownn.py for python 2 will be integrated for the cloud_cover variable.
thanks a lot :-)

**Pull request merged**
