### PR TITLE
Fix to restore useHTML xAxis.labels in windrose

### PR DESCRIPTION
**Pull request by ArendPWS**
This option is still present and functional in the latest Highcharts API. As mentioned in this issue #443 and in this topic at weew-user: [Belchertown 1.2 and Danish Charaters](https://groups.google.com/g/weewx-user/c/sT87LBkYTaU/m/ywODGYBjAwAJ)

### CODE REVIEW

**Comment by ddperso** [comment]
When I remove // the windrose becomes gray... I cannot apply this change
[image: image.png]
[image: image.png]

**Comment by ArendPWS** [comment]
@ddperso, I don't see any images in your post. Can you upload them once more?

**Comment by ArendPWS** [comment]
> When I remove // the windrose becomes gray... I cannot apply this change

This can't be right, you must have made some mistake removing the slashes. Please check again what you did exactly.

**Comment by ArendPWS** [comment]
Closing this pull request, support for full useHTML on all graphs in Belchertown needs to many additional changes in CSS and functions. Still wondering if support for useHTML was removed in successive updates.

**Pull request closed without merging**
