### PR TITLE
Added AQI from Aeris Weather

### PR DESCRIPTION
**Pull request by uajqq**
Added a simple implementation of AQI from Aeris Weather. Obviously needs some polish (color coding, for example) but it’s a start.

### CODE REVIEW

**Comment by ddperso** [comment]
I have added this pull request, but I have an error with wee_reports:

root@meteo:~# wee_reports
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 196, in run
    obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 281, in start
    self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 146, in run
    self.initExtensions(gen_dict[section_name])
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 188, in initExtensions
    class_ = weeutil.weeutil.get_object(x)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1093, in get_object
    mod = __import__(module)
  File "/usr/share/weewx/user/belchertown.py", line 947
    if self.generator.skin_dict['Extras']['forecast_alert_enabled'] == "1":
                                                                          ^
IndentationError: unindent does not match any outer indentation level
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 179, in run
    obj = weeutil.weeutil.get_object(generator)(
  File "/usr/share/weewx/weeutil/weeutil.py", line 1093, in get_object
    mod = __import__(module)
  File "/usr/share/weewx/user/belchertown.py", line 947
    if self.generator.skin_dict['Extras']['forecast_alert_enabled'] == "1":
                                                                          ^
IndentationError: unindent does not match any outer indentation level

**Comment by uajqq** [comment]
> IndentationError: unindent does not match any outer indentation level

Very strange -- I don't get that error and it looks properly indented in the code. Try cloning the fork and install using wee_extension?

**Comment by uajqq** [comment]
Added an option to turn off AQI if desired. You now need to set “aqi_enabled = 1” in weewx.conf (where forecast_enabled is set). Not setting this value, or setting this value to 0, turns off display of the AQI. Also adjusted the colors so they’re more in line with the rest of the skin.

**Comment by ddperso** [comment]
All is OK now (I have made a mistake...)
As I am in France, could you add a function for translating the aqi-category in the locale language.
Many thank's
aqi

**Comment by uajqq** [comment]
Added the ability to supply your own labels for AQI categories, for translation purposes. If not set, the values default to English category names given here: [https://www.aerisweather.com/support/docs/api/reference/endpoints/airquality/](url)

Example config:

```
[StdReport]
    [[Belchertown]]
        [[[Labels]]]
            [[[[Generic]]]]
                aqi_good = Good
                aqi_moderate = Moderate
                aqi_usq = Unhealthy for select groups
                aqi_unhealthy = Unhealthy
                aqi_very_unhealthy = Very unhealthy
                aqi_hazardous = Hazardous
```

**Comment by uajqq** [comment]
Added the option to graph current AQI. It appears as a ring graph from 0-500. Colors change as the AQI increases. Configure in your graphs.conf as so:

```
    [[currentAQI]]
        title = Air Quality Index
        [[[aqiChart]]]
```

To do: add AQI category description, and make the label change colors along with the graph.

**Comment by uajqq** [comment]
Adjusted formatting to make the chart cleaner. Category description is now included and the labels change color along with the graph.

image

image

**Comment by uajqq** [comment]
Closing this and replacing it with #480, since the commit history is too messy.

**Pull request closed without merging**
