### PR TITLE
Belchertown.py code simplified by adding Beaufort labels to skin.conf

### PR DESCRIPTION
**Pull request by uajqq**

### CODE REVIEW

**Comment by ArendPWS** [comment]
@uajqq,

The beaufort option is mentioned in the general options of the README.md but I can't find an example entry in skin.conf?

**Comment by uajqq** [comment]
It should be under the Forecast section, alphabetically after Aeris weather options. Starts at line 500.

**Comment by ArendPWS** [comment]
> It should be under the Forecast section, alphabetically after Aeris weather options. Starts at line 500.

You mean this?

        # Beaufort Scale Default Labels
        beaufort0  = "calm"
        beaufort1  = "light air"
        beaufort2  = "light breeze"
        beaufort3  = "gentle breeze"
        beaufort4  = "moderate breeze"
        beaufort5  = "fresh breeze"
        beaufort6  = "strong breeze"
        beaufort7  = "near gale"
        beaufort8  = "gale"
        beaufort9  = "strong gale"
        beaufort10 = "storm"
        beaufort11 = "violent storm"
        beaufort12 = "hurricane force"

I mean the entry to enable Beaufort like below, so users know what to change:

[Extras]
    beaufort_category = 0

**Comment by uajqq** [comment]
Oh, I see. I'll add that and open a pull request--thank you!

**Pull request merged**
