### PR TITLE
Add optional label to main sensor

### PR DESCRIPTION
**Pull request by ArendPWS**

### CODE REVIEW

**Comment by poblabs** [comment]
Do you have a screenshot of what this would look like?

**Comment by ArendPWS** [comment]
Hello Pat,

Here is how it looks like on my test computer. Please don't pay attention to the weird High and Low values for the main temperature. This is the result of a running experiment with additional sensor support.

Additional sensor label

**Comment by poblabs** [comment]
Why do you need this label? The box only holds 1 sensors values..?

**Comment by ArendPWS** [comment]
I have added support for an extra thermo/hygro sensor to my station. The code for this extra sensor is in it's own .inc file. But to include this .inc file into your skin I have added an extra (conditional) div to support this. If you don't like the idea, that's ok. But I guess more people would like to include some code for some kind of extra sensor to the bottom of the observation row. The label in the first commit can be used to specify a manufacturer or location or some other kind of description. All the code to support the additional sensor is in it's own .inc file, including MQTT support. So no need to make this part of the main code.
Below is a screenshot from my running test with additional sensor. It looks weird because on the first laptop weewx is running with support for my PWS and the MQTT broker. On a second laptop I have weewx and the simulator running so i can test MQTT. I am not a professional programmer and new to Github, I hope this makes things a bit more clear.

Additional sensor example

**Comment by poblabs** [comment]
Based on this comment, https://github.com/poblabs/weewx-belchertown/issues/370#issuecomment-681874224, I didn't know you were able to extend the MQTT function. That is cool! 

I think it may make sense to include an example of how to do this in the readme as it's own section. I can include this - or you can if you want - can you elaborate more on how you're doing it with a working example? I think that'll help future users!

**Comment by ArendPWS** [comment]
Thank you Pat.

First of all: my extension was created with trial and error and I am sure there is a lot of room for improvement and smarter coding. But it works for me in its current shape.

I wonder what would be best practice to show how it works. I wrote my extension to support the extra sensor using extraTemp1 and extraHumid1. But I guess most users don't have/use these on their PWS. So maybe I should rewrite the code example using the main temperature (outTemp) and humidity (outHumidity) ? That way they can compare the existing main temperature and humidity readings with the extension readings?
If you agree with this approach, I will create an example and post it here. That way you will understand how it works and you can give your opinion. In case you have any questions about the code I can answer them here.

One more thing: English is not my native language, sometimes it can be a struggle to explain things the right way. :)

**Comment by ArendPWS** [comment]
This example depends on my pull request being implemented.

Here is my example on how to include an extension for user specific observations. It will display the outdoor temperature with high/low and outdoor humidity with high/low on a new row beneath the observation row. MQTT is supported on both temperature and humidity.

1. Download the zip-file ([user_extension.zip](https://github.com/poblabs/weewx-belchertown/files/5145888/user_extension.zip)) and unpack in the skins/Belchertown folder or
2. Copy the code provided below  into a new file and save this file named "user_extension.inc". Then copy/move it into the folder as mentioned above
3. Configuration in skin.conf:
           user_extension = "user_extension.inc"
4. Wait for the CheetahGenerator to generate a new set of files in the public_html/belchertown folder.
5. Refresh your Belchertown homepage

Now the homepage should look similar to this, showing the extension labeled 'Extra reading':

Extension_example

Contents of user_extension.inc :

```

######################################## Javascript ########################################
<script type="text/javascript">

	<!-- Extend original Belchertown update_weewx_data function -->
	var old_update_weewx_data = update_weewx_data;
	update_weewx_data = function(data) {
		// Run original Belchertown code first
		old_update_weewx_data.apply(this, arguments);

		// Below is the new code that updates output high/low for extension temperature and humidity, when modifying this file make sure weewx_data.json.tmpl matches your code
		
		extra1temphigh = data["day"]["outTemp"]["max"];
		extra1templow = data["day"]["outTemp"]["min"];
		jQuery(".extra1-temp-high").html( extra1temphigh );
		jQuery(".extra1-temp-low").html( extra1templow );
		
		extra1humidhigh = data["day"]["humidity"]["max"];
		extra1humidlow = data["day"]["humidity"]["min"];
		jQuery(".extra1-humid-high").html( extra1humidhigh );
		jQuery(".extra1-humid-low").html( extra1humidlow );
	};

	#if $Extras.has_key("mqtt_websockets_enabled") and $Extras.mqtt_websockets_enabled == '1'	
		<!-- Extend original Belchertown update_current_wx MQTT function -->
		var old_update_current_wx = update_current_wx;
		update_current_wx = function(data) {
			// Run original Belchertown code first	
			old_update_current_wx.apply(this, arguments);

			// Convert MQTT data into json
			data = jQuery.parseJSON( data );

			// Below is the new code for live updating the extension
			
			// Update temperature in case of degrees F
			if ( data.hasOwnProperty("outTemp_F") ) {
				outTemp = parseFloat(parseFloat(data["outTemp_F"])).toLocaleString("$system_locale_js", {minimumFractionDigits: unit_rounding_array["outTemp"], maximumFractionDigits: unit_rounding_array["outTemp"]});
				get_outTemp_color( "degree_F", outTemp );
				jQuery(".extra1-temp").html( outTemp );
			}

			// Update temperature in case of degrees C
			if ( data.hasOwnProperty("outTemp_C") ) {
				outTemp = parseFloat(parseFloat(data["outTemp_C"])).toLocaleString("$system_locale_js", {minimumFractionDigits: unit_rounding_array["outTemp"], maximumFractionDigits: unit_rounding_array["outTemp"]});
				get_outTemp_color( "degree_C", outTemp );
				jQuery(".extra1-temp").html( outTemp );
			}

			// Update humidity
			if ( data.hasOwnProperty("outHumidity") ) {
				jQuery(".extra1-humidity").html( "Humidity: " + parseFloat(parseFloat(data["outHumidity"])).toLocaleString("$system_locale_js", {minimumFractionDigits: unit_rounding_array["outHumidity"], maximumFractionDigits: unit_rounding_array["outHumidity"]}) + " $unit.label.outHumidity" );				
			}	  
		};
	#end if

	// Update color of temperature reading using existing Belchertown function
	jQuery(document).ready(function() {
		var extra1_color = get_outTemp_color( "$unit.unit_type.outTemp", "$current.outTemp.formatted", true );
		jQuery(".extra1temp_outer").css( "color", extra1_color );
	});
</script>

######################################## CSS ########################################
<style>
	.extra1-title {
		font-size:20px;
		text-align:center;
		color: #e5554e;
	}
	.extra_current_temp {
		text-align:center;
		line-height:1;
		padding: 0px !important;
	}
	.extra_current_temp .extra1temp_outer {
		font-size:65px;
	}
	.extra1temp_outer {
		padding-bottom: 15px;
	}	
	@media only screen and (max-width: 800px) {
		.extra_current_temp .extra1temp_outer {
			font-size: 55px;
		}
	}
	.extra1-humidity {
		text-align:center;
		font-size:18px;
	}
	.extra-high-low {
		padding-bottom: 15px;
		font-size:15px;
		line-height: 1.3;
	}	
</style>

######################################## HTML ########################################
<div class="col-lg-2 extra-sensors-row-height border-right">
	<div class="row obs-row-extra">                        
		<div class="obs-extra">
			<!-- Extra reading label -->
			<div class="extra1-title">
				Extra reading
			</div>
			<!-- Extra temperature reading -->
			<div class="row temp-observation">
				<div class="col-sm-12 extra_current_temp">
					<div class="extra1temp_outer"><span class="extra1-temp">$current.outTemp.formatted</span><sup class="outtempunitlabelsuper">$unit.label.outTemp</sup></div><!-- AJAX -->
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<!-- Extra high/low temperature reading -->
					<div class="extra-high-low">
						<table class="stn-high-low-table">
							<tbody>
								<tr>
									<td class="stn-high-low-table-title">High</td>
									<td class="stn-high-low-table-title border-left">Low</td>											
								</tr>
								<tr>
									<td class="extra1-temp-high">$day.outTemp.max</td>
									<td class="border-left extra1-temp-low">$day.outTemp.min</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!-- Extra humidity reading -->
			<div class="row">
				<div class="col-sm-12">
					<div class="extra1-humidity">Humidity: $current.outHumidity</div><!-- AJAX -->							
					<!-- Extra high/low humidity reading -->
					<div class="extra-high-low">
						<table class="stn-high-low-table">
							<tbody>
								<tr>
									<td class="stn-high-low-table-title">High</td>
									<td class="stn-high-low-table-title border-left">Low</td>																						
								</tr>
								<tr>
									<td class="extra1-humid-high">$day.outHumidity.max</td>
									<td class="border-left extra1-humid-low">$day.outHumidity.min</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
```

**Comment by ArendPWS** [comment]
I think its best to do a new pull request.

**Pull request closed without merging**
