### PR TITLE
Adding ReNaSS French earthquake network

### PR DESCRIPTION
**Pull request by norecords**
Adding ReNaSS network asked on issue #561

### CODE REVIEW

**Comment by ddperso** [comment]
Many thanks Onza

Just an information, ReNaSS provides also career shots, not interesting, also you can change in belchertown.py in the url:
mindepth=-1 by mindepth=1
In this case you see only "real" earthquake

**Comment by norecords** [comment]
Many thanks to you too :) 
I'll commit it as we want reals earthquakes, and add a comment in Belchertown.py for people that lives close to careers and want to show them.

**Comment by norecords** [comment]
It seems that mindepht 1 isn't enough to avoid career shot, I got one at 1.4 around me
https://renass.unistra.fr/evenements/60227e0af251627cd8d3c764

**Comment by norecords** [comment]
I think everything is fine.

**Comment by ddperso** [comment]
It's OK for me

**Comment by norecords** [comment]
humm, `mindepth` has no effect, and found on this page 
https://renass.unistra.fr/sismicite/derniers-seismes-en-metropole
that's `minmagnitude` instead.

**Comment by ddperso** [comment]
Argggg!   mindepth is not a very good filter...
We can have quarry blast at 8m of depth, and with a magnitude greater than 2 !

I think that the best way is to check the value of "type" and select only "earthquake"
We can also put a minmagnitude = 1 or 2

the problem is that "type" parameter can not be entered in url
may be have a special treatment of json by selecting the 1st "type=earthquake" in the list (with no limit)

I don't know how to do that...
eathquake

**Comment by norecords** [comment]
With the mix of both parameters i've got only earthquakes
https://renass.unistra.fr/fdsnws/event/1/query?latitude=46.6&longitude=1.9&maxradius=9&minmagnitude=1&mindepth=1&orderby=time&starttime=2021-01-26&format=json

**Comment by ddperso** [comment]
I've sent a message to ReNaSS and good answer, we can use eventtype with
the new version of api

----------------------------------------------------------------------------------------

Bonjour,

Je vous invite a utiliser la nouvelle version du webservice disponible a
cette adresse et qui supporte le paramètre eventtype :
https://api.franceseisme.fr/fdsnws/event/1/query?limit=30&eventtype=earthquake&format=json

------------------------------------------------------------------------

**Comment by ddperso** [comment]
I have tested with this url:

https://api.franceseisme.fr/fdsnws/event/1/query?latitude=%s&longitude=%s&maxradius=%.2f&orderby=time&format=json&limit=1&eventtype=earthquake

it's perfect
You can add a minmagnitude if you want to display only biggest earthquake

**Comment by norecords** [comment]
> I have tested with this url: https://api.franceseisme.fr/fdsnws/event/1/query?latitude=%s&longitude=%s&maxradius=%.2f&orderby=time&format=json&limit=1&eventtype=earthquake it's perfect You can add a minmagnitude if you want to display only biggest earthquake 

Sounds good, but the urls events are pointing to a server that doesn't work, 
ex: https://franceseisme.fr/en/events/136173
@ddperso Can you report them this issue ?

**Comment by norecords** [comment]
Also we need to round the Magnitude value,
ex: 0,976023 
to
0,9

**Comment by ddperso** [comment]
Yes, but I observed  that maxradius has no effect  and I have not the same
datas as Renass url , and the description is in english...
I stay  in contact with Renass engineer to improve this result
For the moment the mix of mindepth and minmagnitude gives a best result

To be continued...

**Comment by ddperso** [comment]
franceseime url is in beta test/dev for the moment, it will be operationnal at beginning of march
It will include a french description in json

**Comment by norecords** [comment]
@poblabs Thank you !
We will make a new pull request when the new api will be ready.

**Comment by poblabs** [comment]
@norecords Ok! Thanks! 😄

**Pull request merged**
