### PR TITLE
Add ReNaSS new earthquake api behavior

### PR DESCRIPTION
**Pull request by norecords**
Modified ReNaSS network asked on issue https://github.com/poblabs/weewx-belchertown/issues/561#issuecomment-784492520

I add `if system_locale == "fr_FR":` statement to grab French description and url to corresponding event
else it's in English

### CODE REVIEW

**Comment by norecords** [comment]
That need some commit before merging it.

**Comment by steflp** [comment]
Hello  back 
I modify manually  the belchertown.py file.
 but the url is  not  good  yes  ;-( ....
 you can see it here  : [https://meteo-pontscorff.fr/data-weewx/FROGGIT/belchertown/]
image

**Comment by norecords** [comment]
@steflp you haven't modified the 2nd part where json data parsed..
please look at https://github.com/poblabs/weewx-belchertown/pull/602/files

Best regards

**Comment by norecords** [comment]
```
from math import cos, pi

lat = 43.487950
long = 6.079865

radiusInKm = 300

kmInLongitudeDegree = 111.320 * cos( lat / 180.0 * pi)

deltaLat = radiusInKm / 111.1
deltaLong = radiusInKm / kmInLongitudeDegree

minLat = lat - deltaLat
maxLat = lat + deltaLat
minLong = long - deltaLong
maxLong = long + deltaLong

print(minLat, maxLat, minLong, maxLong)
```
this make good results

**Comment by norecords** [comment]
Need to preg all locales fr_* to show description and link in French

**Comment by norecords** [comment]
@poblabs that's fine for me, everything works as expected.

**Comment by poblabs** [comment]
@norecords Ready for merge?

**Comment by norecords** [comment]
@poblabs yes it's ready

**Comment by steflp** [comment]
Hello back, 

its seems all ok but ....  what does it mean this distance :  433.1 km N  ????
image

I live near the town LORIENT ( 60 kms from Vannes in, Britany) and what is it this distance  433 km  ? 
I dont really understand ...

Perhaps I ve forgotten  something in the code ...

(dont forget , i must force unit 'km' in the file) 
around line  1060  

distance_unit = converter.group_unitdict["group_distance"]
distance_unit = 'km' 

Best regards 
Stephane

et Bonsoir de  la Bretagne  !

**Comment by poblabs** [comment]
This is the distance from your station the earthquake happened. 

So this earthquake was 433.1 km NORTH of your station

**Comment by steflp** [comment]
it s not possible  ! 
I live a  60 kms  ! 
image

**Comment by poblabs** [comment]
This is driving 60km right?

The earthquake is line-of-sight distance

**Comment by steflp** [comment]
yes 60 kms driving ... 
I ve tried with another point  and it seems more better  now ... 
I will test for a few days ...
Thanks :)

**Comment by norecords** [comment]
@steflp what point do you use ??
can you paste your code, please

**Comment by steflp** [comment]
yes I can  :) 
I rename the file in .txt 
[belchertown.txt](https://github.com/poblabs/weewx-belchertown/files/6052250/belchertown.txt)

**Comment by norecords** [comment]
@steflp your town should be
47.836
-3.403

**Comment by steflp** [comment]
hello back  I m very confused ! 

i dont know how my locator number change ! perhaps when I put my new parameters in my config files ( I ve two stations, so with  2 services  , with 2 config files.

Now all is correct !  the last earthquake is  46.6 km ! 

@poblabs  the script now work fine  !   it my lat et lon,g in ly weewx  config file 47.836 not  43.82 :) 
@norecords  good job !

 [off topic]  :  is it possible to insert SHOM like this  : 
 https://services.data.shom.fr/oceano/render/html/widget?duration=4&delta-date=0&spot=LORIENT&utc=1&lang=fr
 ( it seems , the service is not free) 

Thanks a  lot  ;)  fort all

Stephane

**Comment by norecords** [comment]
> [off topic] : is it possible to insert SHOM like this :
> https://services.data.shom.fr/oceano/render/html/widget?duration=4&delta-date=0&spot=LORIENT&utc=1&lang=fr
> ( it seems , the service is not free)

You may open new issue.

**Pull request merged**
