### PR TITLE
Display the "distance from" in miles for earthquake if not using metric distance #535

### PR DESCRIPTION
**Pull request by dkozinn**
As described in #535.

Note that this does require the **re** package.

### CODE REVIEW

**Comment by biltmorelaker** [comment]
I haven’t updated versions in a while. But my webpage displays the distance to the earthquake in miles. https://wx.kutzenco.com

**Comment by dkozinn** [comment]
It's not the distance from your station to the earthquake, it's the distance from the earthquake to the nearest location that USGS identifies. Here's what I mean:

image

You can see that distance in km.

From my site (https://k2dbk.com/weather), it now looks like this:
image

**Comment by biltmorelaker** [comment]
Ah. Got it. Sorry for my misunderstanding.

**Comment by GeekNJ** [comment]
I've been running with this change since posted and it's worked exactly as expected. The underlaying data changes every day or two and this enhancement has properly modified the km's to mi's. Thanks for this change.,

**Comment by dkozinn** [comment]
@poblabs Pat I'm happy to re-integrate with the latest version if that would make things easier. The changes are relatively straightforward.

**Comment by poblabs** [comment]
@dkozinn Yes please. There's also some conflicts now so it may make sense to re-sync your branch with master

**Comment by dkozinn** [comment]
I'm going to redo this, I'm not confident that I did the merge correctly. I'll submit another pull request once it's clean.

**Pull request closed without merging**
