### PR TITLE
Development

### PR DESCRIPTION
**Pull request by kwalkerk**
My logo didn't look very good in dark mode.  So I modified some things in the skin to allow both a dark mode and light mode log.

I added an [Extras] entry in skin.conf:  logo_image_dark = ""
I then modified header.html.tmpl to add an id="logo_image" attribute to the image tag
and finally modified belchertown.js.tmpl to use the id attribute to load the proper image inside the changeTheme function.  

Files are attached.  For an example of this working see my site at http://squatleyweather.ddns.net/belchertown

[belchertownpullrequest.zip](https://github.com/poblabs/weewx-belchertown/files/4799381/belchertownpullrequest.zip)

### CODE REVIEW

**Comment by poblabs** [comment]
Thanks for the PR. Unfortunately this PR would merge everything into master - esentially releasing the skin. Don't want to do that yet 😄 If you're OK, I can close this PR and include the changes as part of a commit on my side. If you want the credit for the work, then you can submit a PR just for the changes itself and not for every commit. Let me know!

**Comment by kwalkerk** [comment]
Not worried about the credit. Do what you think is best.

**Comment by kwalkerk** [comment]
That’s fine.  I’ve never done a PR before so I must have done it wrong.  Not worried about the credit.  Just thought it might be useful

Cheers!

**Comment by poblabs** [comment]
No worries - PRs can be confusing sometimes. I'll see if I can find your changes and get them merged in

**Comment by poblabs** [comment]
Just added this to the development branch. Closing this. Thanks again!

**Comment by FutureCow** [comment]
Little error with this PR.
When using the Light/Dark Switch, the logo_image_dark = "" is used.
When it's after sunset and the page automatically change to dark, logo_image = "" is used, so you get the light logo with the dark page.

**Pull request closed without merging**
