### PR TITLE
Error getting AQI data from Aeris Weather

### PR DESCRIPTION
**Pull request by michaelundwd**
Aeris is giving me a warn_no_data error code for the last 24 hours (I have raised a support ticket) but The only way I discovered it was when I looked at syslog that was giving me 11 error messages every archive interval, as the aqi variables were not being set.  
This PR checks for an error code and only sets the variables if there is no error and clears the variables if there is and causing aqi to display Unknown.
What I don't understand is why I get 11 error messages.  That implies that belchertown.py is called 11 times every archive interval.  I had the same issue when I was debugging the forecasts. See log details below.

Feb 20 16:35:30 garagepi weewx[25365] INFO weewx.manager: Added record 2021-02-20 16:35:00 GMT (1613838900) to database 'weewx.sdb'
Feb 20 16:35:30 garagepi weewx[25365] INFO weewx.manager: Added record 2021-02-20 16:35:00 GMT (1613838900) to daily summary in 'weewx.sdb'
Feb 20 16:35:32 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:37 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:43 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:47 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:49 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:50 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:51 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:54 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:55 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:56 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range
Feb 20 16:35:57 garagepi weewx[25365] ERROR user.belchertown: Error getting AQI from Aeris weather. The error was: list index out of range

Ensures error message is not displayed when there is no aqi data and sets aqi data to default values

### CODE REVIEW

**Comment by poblabs** [comment]
I'll take a look at this later today but your description makes sense.

the python script does get called many times and that is the way that
cheetah generator works for the sle.

Is this reason that I set a flag for the existence of a forecast file so
that way it'll only check that forecast file once, and if it needs an
update then it'll only get that update once. In your case it's trying to
get the update but it's failing so it's not setting the flag that it was a
success so it's continuously trying to get it.

In a typical scenario your belchertown file will run many times but the
forecast and earthquake downloads should only be triggered once if and when
needed.

**Comment by michaelundwd** [comment]
Thanks  for the update.  At present the aqi call is outside the stale checking loop though.  Should it go inside as well?

**Comment by poblabs** [comment]
Hmm it probably should

**Comment by michaelundwd** [comment]
I have updated belchertown.py in fd8f763 so that it nullifies any aqi data should there be an error in extracting aqi data.  Typically this occurs if aeris has no data to return.  This remedies the fix in my original PR.
This still gives 11 error messages in the log every archive interval, but I see no elegant fix for that.
The aqi call is inside the stale checking loop - I was wrong in my previous email.

**Pull request merged**
