### PR TITLE
Javascript formatting cleanup

### PR DESCRIPTION
**Pull request by uajqq**
Another code formatting cleanup, this time for the Javascript component, if there's any interest. No actual changes to the code: the only thing I did was run it through `prettier` to standardize the formatting and make it a little easier to read.

### CODE REVIEW

**Comment by ArendPWS** [comment]
I don't like the result. To many unnecessary lines are added, and the readabilty is worse, for instance:

No improvement

**Comment by michaelundwd** [comment]
I agree with @ArendPWS, especially the readability.  I prefer an indent of 4 spaces.

**Comment by uajqq** [comment]
The default `prettier` settings are certainly pretty aggressive. Let me see if I can tone it down a bit to reduce the line breaks especially.

**Comment by uajqq** [comment]
Okay, I force-pushed an update with much more permissive settings. Cuts down on the extra line generation. Tab space also set to 4; I think 2 is cleaner for JavaScript but probably best to keep it consistent with everything else, you're right.

**Comment by poblabs** [comment]
I agree on the formatting from @ArendPWS and @michaelundwd - the latest commits look better. 

FWIW I have some trouble reading the Black formatting in Python too. Not sure why - maybe it's all the multi lines?

There's some conflicts now with the JS - can you take a look at those? Probably related to recent PRs.

**Comment by uajqq** [comment]
Deleting this PR and opening another to keep commit history cleaner...

**Pull request closed without merging**
