### PR TITLE
Changed wind rose colors to match weatherRange

### PR DESCRIPTION
**Pull request by uajqq**
An edit to the wind rose colors so they match the color scheme of the weatherRange graph, allowing more intuitive display of wind speeds

### CODE REVIEW

**Comment by poblabs** [comment]
This is interesting, thanks for the PR. The weatherRange colors come from the outTemp colors so they match the temperature colors at the top left of the page. The rest of the colors (spline, bar, column, etc) are highcharts default. Do you think that if we change the windRose colors, we would have to change everything?

I'm also not sure the 2 blues look good together - not enough contrast to separate group 0 and group 1.

**Comment by uajqq** [comment]
I figured the difference between Beauford 0 and 1 wouldn't be that important, since wind speeds of 0 will have minimal representation on the wind rose in most situations.

Totally missed that the colors for current temperature and weatherRange are linked. For the wind rose, I just switched the values from _colorIndex values to defined hex values, copied and pasted from the get_outTemp_color function for consistency. To make them all truly coordinated, I'm guessing the get_outTemp_color function would have to be expanded to accept the various wind speed units as well? That may be beyond my horrible Javascript abilities.

**Comment by poblabs** [comment]
I wonder if a better solution would be to allow customization to the windrose colors so that folks like you can change the colors to your liking. Right now they're hard-coded which is why I think you're submitting this PR. All chart colors can be changed using the `colors` option in graphs.conf, except for windrose, so I think that's the better solution.

**Comment by uajqq** [comment]
Changed the code so that [[[windRose]]] in graphs.conf accepts custom colors as hex values, specified as beauford0 through beauford6. Tested and working on my setup. If no values given, it defaults to the “rainbow” color scheme:

`[[[windRose]]]
    beauford0 = “#ff0000”
    beauford5 = “#444444”`

etc.

**Comment by poblabs** [comment]
Awesome! Thanks for the PR, I think this is great to get color customization back into wind rose again. I'll merge and update the charts wiki

**Pull request merged**
