### PR TITLE
History feature

### PR DESCRIPTION
**Pull request by olpayras**
I worked on history feature. I do an include file named history.inc that i added in reports/index.html.tmpl. You can include in future revision here or anywhere. I used module from Bootstrap skin. So you have to put history.inc in bin/user directory. After that, you should change the skin.conf . You can have a preview here http://meteo.payrastre.fr/belchertown/reports

### skin.conf

Edit :

```
[CheetahGenerator]
   This section is used by the generator CheetahGenerator, and specifies
   which files are to be generated from which template.

    search_list_extensions = user.belchertown.getData, user.historygenerator.MyXSearch
```
Add in file

```

[HistoryLabels]

    [[history_tables]]
        title     = History
        min_temp  = Minimum Temperature
        max_temp  = Maximum Temperature
        avg_temp  = Average Temperature
        rain      = Rainfall
        rain_days = Days of rain
        uv_max    = UV Index Max
        
###############################################################################

[HistoryReport]

    #
    # Settings for the HTML month/year colour coded summary table generator
    #

    # minvalues, maxvalues and colours and fontColours should contain the same number of elements.
    #
    # For example,  the [min_temp] example below, if the minimum temperature measured in
    # a month is between -50 and -10 (degC) then the cell will be shaded in html colour code #0029E5.
    #
    # colours = background colour
    # fontColours = foreground colour [optional, defaults to black if omitted]

    # Default is temperature scale
    minvalues = -50, -10, -5, 0,  5, 10, 15, 20, 25, 30, 35
    maxvalues = -10, -5,   0, 5, 10, 15, 20, 25, 30, 35, 60
    colours =   "#0029E5", "#0186E7", "#02E3EA", "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
    fontColours =   "#FFFFFF", "#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#FFFFFF", "#FFFFFF"
    monthnames = Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    # Restrict the size of the table by ignoring everything before startdate
    # Specify in unix epoch time. e.g. 1325376000 is 1-Jan-2012
    #startdate = 1325376000

    # The Raspberry Pi typically takes 15+ seconds to calculate all the summaries with a few years of weather date.
    # refresh_interval is how often in minutes the tables are calculated.
    refresh_interval = 60

    [[min_temp]]
        obs_type = outTemp                 # obs_type can be any weewx reading
        aggregate_type = min               # Any of these: 'sum', 'count', 'avg', 'max', 'min'

        summary_column = true
        summary_heading = Min

    #
    # Can also use these aggregate_types:  'max_ge', 'max_le', 'min_le', 'sum_ge' to count days
    # where an observation is ge: greater of equalto, or le: lessthan or equal to a threshold value
    # To specify this threshold, use: aggregate_threshold = [value], [units]
    #
    # e.g Specify temperature threshold of 20C:  aggregate_threshold = 20, degree_C
    #

    [[max_temp]]
        obs_type = outTemp
        aggregate_type = max

        summary_column = true
        summary_heading = Max

    [[avg_temp]]
        obs_type = outTemp
        aggregate_type = avg

        summary_column = true
        summary_heading = Avg

    [[rain]]
        obs_type = rain
        aggregate_type = sum

        minvalues = 0, 25, 50, 75, 100, 150   # Override default temperature colour scheme with rain specific scale
        maxvalues = 25, 50, 75, 100, 150, 1000
        colours = "#E0F8E0", "#A9F5A9", "#58FA58", "#2EFE2E", "#01DF01", "#01DF01"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total

    [[rain_days]]
        obs_type = rain
        units = Days                        # Override default table units label
        aggregate_type = sum_ge
        aggregate_threshold = 1, mm
        minvalues = 0, 6,  12, 18, 24, 30   # Override default temperature colour scheme with rain specific scale
        maxvalues = 6, 12, 18, 24, 30, 200
        colours = "#E0F8E0", "#A9F5A9", "#58FA58", "#2EFE2E", "#01DF01", "#01DF01"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total

    [[uv_max]]
        obs_type = UV
        aggregate_type = max
        minvalues = 0, 2, 4, 6,  8, 10, 12, 15
        maxvalues = 2, 4, 6, 8, 10, 12, 15, 50
        colours = "#04EC97", "#05EF3D", "#2BF207", "#8AF408", "#E9F70A", "#F9A90B", "#FC4D0D", "#FF0F2D"
        fontColours = "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000", "#000000"

        summary_column = true
        summary_heading = Total
```
### reports/index.html.tmpl

After #include "page-header.inc", add  

```
#if os.path.exists("history.inc")
                    #include "history.inc"
                #end if


```
### history.inc
```

<br>
<div class="main" >
   <H1>$HistoryLabels.history_tables.title</H1>
      <center>
        <div class="container" >
            <div class="col-md-8 main" >
             <br><h3>$HistoryLabels.history_tables.min_temp</h3>
                $min_temp_table

             <br><h3>$HistoryLabels.history_tables.avg_temp</h3>
                $avg_temp_table

             <br><h3>$HistoryLabels.history_tables.max_temp</h3>
                $max_temp_table

             <br><h3>$HistoryLabels.history_tables.rain</h3>
                $rain_table

             <br><h3>$HistoryLabels.history_tables.rain_days</h3>
                $rain_days_table

             <br><h3>$HistoryLabels.history_tables.uv_max</h3>
                $uv_max_table
             </div>
        </div>
      </center>
</div>

```
I think someone can do something better design cause my html known are very poor. Color can be changed in skin.conf [historyReports] section.

In the attached file, you will find the changes files in english, history.py and history.inc and index.html.tmpl modified.

[history.zip](https://github.com/poblabs/weewx-belchertown/files/3104741/history.zip)

### CODE REVIEW

**Comment by poblabs** [comment]
This is interesting. Some thoughts:

1. What's the license on this from Niculskin? Need to make sure you are following license. 
2. Do you think this makes more sense on the Records page?
3. There are A LOT of conflicts here that need to be cleaned up. Did you add these changes to the development branch? Might need to put this PR against that branch. 


Lastly, I can work on style, but I am not sure what page this makes sense to be on.

**Comment by poblabs** [comment]
I'm actually going to close this because it will merge this into master, which will release 1.0. I don't want that. Submit a new PR against the Development branch and make sure when you submit the PR it says "No conflict". Might need to re-sync your fork before you do that.

**Comment by olpayras** [comment]
Nico Gulden take this feature from bootstrap modified skin developped by Nick Dajda. I took history.py from his website here https://github.com/brewster76/fuzzy-archer. License looks to be GNU.

Sorry, i'm a newbie here and i don't know all the rules. I will try to submit my work on developpement branch.

**Comment by poblabs** [comment]
No problem. Fork this skin to your GitHub, then apply changes to your GitHub under your development. Then submit Pull Request on your Development to my Development. Google can help you too if you get stuck.

**Pull request closed without merging**
