### PR TITLE
Code formatting cleanup

### PR DESCRIPTION
**Pull request by uajqq**
If there is any interest for it, this pull request cleans up the belchertown.py code to make it easier to read and more consistently formatted (using the Black code formatter as a base). There are NO substantive code changes, just formatting and wording differences (such as using `isinstance` instead of `type`, for example), all of which have been manually checked.

The only actual code changes are the Python2 hacks. Instead of testing for failure of Python3 code and falling back on Python2 if an exception is raised, the code now explicitly checks the Python version and runs the appropriate code. Those sections use `sys.version_info[0]` to check the Python version. Other than that, the functionality is not changed.

### CODE REVIEW

**Comment by poblabs** [comment]
Thanks for this! I'll take some time to review it. I don't mind code cleanup at all but I just want to review it.

**Comment by poblabs** [comment]
@uajqq Whats the difference between Black Code Formatter and pep 8 formatting?

**Comment by uajqq** [comment]
Black enforces PEP8, and also a few other stylistic changes designed to make the code easier to read, as well as make git diffs a little clearer. I like it because it has no configuration options, which makes it much easier to use and completely consistent.

**Comment by poblabs** [comment]
Cool, thanks! I dipped into belchertown.py last night and forgot that it looked different than what I'm used to 😄

**Pull request merged**
