### PR TITLE
Allow user choice for footer disclaimer text

### PR DESCRIPTION
**Pull request by biltmorelaker**
This footer text 

> Never make important decisions based on info from this website.

reads a bit more smoothly than the original, which is

> Never base important decisions from this website.

### CODE REVIEW

**Comment by poblabs** [comment]
I never put too much thought into this verbiage. I've copied the core meaning from other weather templates out there that had something similiar to it. Instead of hard-coding it, I could do a variable so it's changeable to the user. 

Maybe something like `footer_disclaimer_text`? `footer_warning_text`?

**Comment by biltmorelaker** [comment]
I think that’s a great idea. You will have the most customizable skin in use! I think that’s a really great thing as users of the skin get to really make it their own! And since I expect you’ll have defaults for most in skin.conf, a new user can get things running without needing to specify values for those variables unless they want to.

 

Best,

Phil

 

PS: I like footer_disclaimer

**Comment by poblabs** [comment]
Do you want to update your pull request to incorporate that variable in the skin.conf (for default) and footer.html.tmpl - or want me to close this and do it? 

Your call. Happy to have you try it out if you'd like.

**Comment by biltmorelaker** [comment]
Pat,

 

Yes. Let me give it a try. It may take a day or so, but it’s not a bug so it could easily wait for a future release. I don’t want to hold up your release of 0.9. But, seeing if I can do it will help my education. Thanks.

 

Best,

Phil

**Pull request merged**
