### PR TITLE
Fix error comparing MQTT payload observations

### PR DESCRIPTION
**Pull request by ArendPWS**
Fix error comparing MQTT payload observations. As mentioned in issue #625.

### CODE REVIEW

**Comment by olpayras** [comment]
This hotfix resolves the MQTT display bug #625

**Comment by ArendPWS** [comment]
Some additional information:

Weewx-mqtt by matthewwall offers the option to disable appending unit labels (defaults to true).

[https://github.com/matthewwall/weewx-mqtt/blob/master/bin/user/mqtt.py](https://github.com/matthewwall/weewx-mqtt/blob/master/bin/user/mqtt.py)

Example:

    [[MQTT]]
        server_url = mqtt://xxxx:xxxx@xxx.xxx.xxx.x:1883/
        topic = weather
        unit_system = METRICWX
        binding = archive, loop
        aggregation = aggregate
        append_units_label = False

**Comment by olpayras** [comment]
Hello @ArendPWS 

Here's my configuration according what you wrote :

```
[[MQTT]]
        server_url = mqtt://localhost:1883/
        unit_system = METRIC
        binding = archive, loop
        aggregation = aggregate
        log_success = False
        log_failure = True
        append_units_label = False
```
Only with this, and installating previous belchertown release, Inside T° is going to 0 when MQTT is running. Can look at https://meteo.payrastre.fr

**Comment by ArendPWS** [comment]
Hi @olpayras

I put that information in this PR as a reminder to myself. I am going to close this PR because it is not good enough to support all possible MQTT payload / observation combinations (take a look at issue  to #648 why this PR will not work for all observations). So it's back to the drawing board to figure out a better solution, if I find it, I will create a new PR. In the mean time you can use this PR as a temporary fix and you can remove the append_units_label entry from your weewx.conf.

**Comment by olpayras** [comment]
Hi @ArendPWS,

Thanks a lot. I willl use this fix for my own usage, and look at #648 for further updates on thoses issues.

**Pull request closed without merging**
