### PR TITLE
AQI improvements

### PR DESCRIPTION
**Pull request by uajqq**
This PR allows users to add AQI as an observation, alongside visibility, barometer, cloud cover, etc. It also adds “AQI” to skin.conf to allow that abbreviation to be translated by users if desired.

### CODE REVIEW

**Comment by norecords** [comment]
Maybe it miss a control to check if aeris forecast is enable

**Comment by norecords** [comment]
```
            elif obs == "aqi":
                try:
                    obs_output = aqi
                except:
                    raise Warning(
                        "Error adding AQI to station observations table. "
                        "Check that you have forecast data, or remove aqi from your station_observations Extras option."
                    )
```
something like that

**Comment by poblabs** [comment]
Do we need to add that?

**Comment by uajqq** [comment]
Might be cleaner from a code standpoint if AQI is just blank when forecast is turned off, like cloud cover is. I made that change in the latest commit.

**Comment by poblabs** [comment]
@uajqq Would you be able to look at the AQI text not changing colors during AJAX? When you have time. Just something I noticed today

**Comment by uajqq** [comment]
Sure--that's interesting, my site seems to work fine

**Pull request merged**
