### PR TITLE
Beaufort category display

### PR DESCRIPTION
**Pull request by uajqq**
1. Adds support for displaying the current Beaufort wind scale category underneath the wind speed. The category shows regardless of which unit system has been selected--you don't necessarily have to be displaying wind speed in Beaufort scale. 

https://user-images.githubusercontent.com/46248396/103393400-75915f80-4af0-11eb-85d6-b44bfd68f122.mov

Off by default. Enable by adding `beaufort_category = 1` to settings in weewx.conf. Users can supply their own translations for the 12 Beaufort scales like so. Default is English if nothing is specified.
```
[StdReport]
    [[Belchertown]]
        [[[Labels]]]
            [[[[Generic]]]]
                beaufort0 = calme
                beaufort1 = très légère brise
                beaufort2 = légère brise
                ...
                beaufort12 = ouragan
```

2. Forecast units now update automatically with whichever unit system has been selected globally. The `forecast_wind_units` option has been depreciated.

***IMPORTANT:*** Ensure that weewx is set to calculate Beaufort scale by adding the following to weewx.conf if not already there. This will insert a Beaufort scale reading into the MQTT payload. I don't really understand why that works--if someone could explain, I'd appreciate it.
```
[StdWXCalculate]
    [[Calculations]]
        beaufort = prefer_hardware
```

***ALSO IMPORTANT:*** if you want to change units, remember to change them for both weewx _and_ MQTT. Change units like so:
```
[StdReport]
    [[Defaults]]
        [[[Units]]]
            [[[[Groups]]]]
                group_speed = beaufort # or 'mile_per_hour', 'km_per_hour', 'knot', or 'meter_per_second'

[StdRESTful]
    [[MQTT]]
        [[[inputs]]]
            [[[[windSpeed]]]]
                name = windSpeed_beaufort # or ‘_mph’, ‘_kph’, ‘_knot’
                units = beaufort
```

*Changing units to Beaufort in weewx will throw errors due to a bug in weewx. The bug has been fixed but it won't be officially released until weewx 4.3. You can ignore the errors or install the latest development version of weewx.*

### CODE REVIEW

**Comment by Stormtracker017** [comment]
In the weewx.conf within the Belchertown stanza,  add the Extras stanza:

[[Belchertown]]
   ....
   ....
        [[[Extras]]]
            beaufort_category = 1

**Comment by poblabs** [comment]
I can't merge this, looks like there's some conflicts with the function. Can you take a look at your PR @uajqq ? Thanks!!

**Comment by uajqq** [comment]
Ah yes, looks like the forecast updates completely changed the code in there...I'll let you know when I've got it working again.

**Comment by uajqq** [comment]
Okay, all conflicts are resolved and should be ready to merge now.

**Comment by poblabs** [comment]
Awesome, thanks!

**Comment by HoracioDos** [comment]
Hello . 
Beaufort scale is missing in skin.conf. I think they should be included as reference if someone wants to translate them in weewx.conf later.
Thanks!

**Comment by uajqq** [comment]
> Hello .
> Beaufort scale is missing in skin.conf. I think they should be included as reference if someone wants to translate them in weewx.conf later.
> Thanks!

Good idea—this also allows the belchertown.py code to be simplified. Thanks!

**Pull request merged**
