### PR TITLE
Responsive windrow error - correction for #444

### PR DESCRIPTION
**Pull request by michaelundwd**
This is a correction to PR #444 that was merged into the Belchertown master.
It restores responsive mode to the wind display whilst retaining the horizontal alignment of temperature and wind measurements.
My thanks to @fvirgola80 for spotting it.
Michael

### CODE REVIEW

**Comment by fvirgola80** [comment]
Thanks a lot @michaelundwd but thanks also to @ArendPWS
Francesco :-)

**Comment by poblabs** [comment]
@michaelundwd Some conflicts here - can you take a look at which section is the right one to keep?

**Comment by michaelundwd** [comment]
@poblabs 
It's a bit confusing as both are called master!  I have checked against my system that has not yet received the latest merges, so this is my best evidence.
In index.html.tmpl, it is the second section to keep as that includes the beaufort_category that was not there when I submitted the PR.  However, I do not know how that affects the layout if at all and I can't test it yet.
For style.css, my system indicates it is the first section to keep.
Does that help?
Michael

**Comment by uajqq** [comment]
I've been trying to merge @michaelundwd branch onto my own so I can fix the conflicts, but for some reason whenever I try to perform the merge using the command line, it's making me rebase the entire thing and make changes to 10 files throughout the entire commit history. I can't figure out how to just fix the two conflicts listed on the website, which are straightforward. If someone better at Git can suggest something, I'm all ears.

**Comment by uajqq** [comment]
I tried to resolve the conflicts, but it’s only showing one file has changed—no idea why. Take a look.

**Pull request merged**
