### PR TITLE
Better AQI error reporting

### PR DESCRIPTION
**Pull request by uajqq**
Improved the code so that failure to get an air quality value from the API results in an error, not a crash

### CODE REVIEW

**Comment by uajqq** [comment]
@distortionist, I've added code so that the error reporting for AQI is a little better. Can you post your error logs after installing this update?

**Comment by Distortionist** [comment]
Alright, I still am getting errors.

I cloned the main branch again, then check out b7d603f, then wee_extension install... 
This is what I get. 

`Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  Error getting AQI from Aeris weather. The error was:#012list index out of range#012The response from the Aeris AQI server was:#012[{'success': True, 'error': {'code': 'warn_no_data', 'description': 'Valid request. No results available based on your query parameters.'}, 'response': []}]#012The URL being used is:#012https://api.aerisapi.com/airquality/closest?p=45.8771100,-61.9614200&format=json&radius=25mi&limit=10&client_id=3TEpRtWjZ9JiQhLuFMfgC&client_secret=4HtKqCHpcLChFZsRWtdEYJbnJJTSrSF85nYbYbKR
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1034, in get_extension_list
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      aqi = data['aqi'][0]['response'][0]['periods'][0]['aqi']
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  IndexError: list index out of range
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  During handling of the above exception, another exception occurred:
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      obj.start()
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 280, in start
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      self.run()
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 150, in run
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], self.gen_ts)
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 220, in generate
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], gen_ts)
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 309, in generate
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      default_binding)
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 376, in _getSearchList
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      searchList += obj.get_extension_list(timespan, db_lookup)
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1038, in get_extension_list
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****      raise Warning( "Error getting AQI from Aeris weather. The error was:\n%s\nThe response from the Aeris AQI server was:\n%s\nThe URL being used is:\n%s" % (error, data['aqi'], aqi_url))
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  Warning: Error getting AQI from Aeris weather. The error was:
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  list index out of range
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  The response from the Aeris AQI server was:
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  [{'success': True, 'error': {'code': 'warn_no_data', 'description': 'Valid request. No results available based on your query parameters.'}, 'response': []}]
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  The URL being used is:
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  https://api.aerisapi.com/airquality/closest?p=45.8771100,-61.9614200&format=json&radius=25mi&limit=10&client_id=3TEpRtWjZ9JiQhLuFMfgC&client_secret=4HtKqCHpcLChFZsRWtdEYJbnJJTSrSF85nYbYbKR
Dec 27 01:46:22 LivingstoneCove weewx[5761] ERROR weewx.reportengine:         ****  Generator terminated
`

**Comment by Distortionist** [comment]
Out of curiosity, could it be due to something like there is no AQI data for my area or station within 25 miles? looking at the new error, I think its something to do with it not getting results. 

`Error getting AQI from Aeris weather. The error was:#012list index out of range#012The response from the Aeris AQI server was:#012[{'success': True, 'error': {'code': 'warn_no_data', 'description': 'Valid request. No results available based on your query parameters.'},`

That is the only reason I can think of other than a typo somewhere, but i am guessing it works for you so that rules that out. I kinda live in the boonies.

**Comment by Distortionist** [comment]
When I copy and paste the query into a web browser, and change 25mi to 35mi I get results. Here is the answer I get: 

`{"success":true,"error":null,"response":[{"id":"AQAN_000030201","loc":{"long":-61.36235,"lat":45.61394},"place":{"name":"port hawkesbury","state":"ns","country":"ca"},"periods":[{"dateTimeISO":"2020-12-27T00:00:00-04:00","timestamp":1609041600,"aqi":25,"category":"good","color":"00E400","method":"airnow","dominant":"o3","pollutants":[{"type":"no2","name":"nitrogen dioxide","valuePPB":3,"valueUGM3":5.64,"aqi":3,"category":"good","color":"00E400"},{"type":"o3","name":"ozone","valuePPB":27,"valueUGM3":54,"aqi":25,"category":"good","color":"00E400"},{"type":"pm2.5","name":"particle matter (<2.5µm)","valuePPB":null,"valueUGM3":5,"aqi":21,"category":"good","color":"00E400"}]}],"profile":{"tz":"America\/Halifax","sources":[{"name":"AirNow (EPA)"},{"name":"Environment Canada"}],"stations":["AQAN_000030201"]},"relativeTo":{"lat":45.87711,"long":-61.96142,"bearing":122,"bearingENG":"ESE","distanceKM":54.93,"distanceMI":34.132}}]}`

**Comment by Distortionist** [comment]
I edited /usr/share/weewx/user/belchertown.py and changed 25mi to 35mi, it now does not generate any errors, the new chart from my own sensor is working as well, I also get the reading with the current conditions from Aeries!  This is great! You do need to clean up the code if this is main now, because anyone without a weather station beside them will generate an error and take their site down like me! :) 

It would be awesome if the reading beside the aeries weather forecast icon can be also read, and converted from the pm2_5 readings, and maybe make it not crash if there is no pm2_5 sensor or weather stations to get the AQI reading from. One thing I noticed was even if I turned AQI off in forecast, it still generated an error, I had no way around it Well... almost no way!

Thank you so much! All your effort is highly appreciated, I love you for this.

**Comment by poblabs** [comment]
Is this ready to commit?

**Comment by uajqq** [comment]
> Is this ready to commit?

Okay, should be ready to merge now.

@Distortionist, I expanded the search range to 50 miles. Be aware this obviously can lead to less and less relevant results for your location, but hopefully increases the ease in setup.

I also added the ability to show which station the AQI is being reported from. Add `aqi_location_enabled = 1` to your weewx.conf and it should display the reporting station underneath AQI. Good way to check if the location is in any way relevant to your station. (wiki updated to match)

> One thing I noticed was even if I turned AQI off in forecast, it still generated an error, I had no way around it

I fixed the error language so it logs an error rather than interrupting the whole program. The rest of the skin should work now even if there is no AQI or if there’s an error.

**Comment by poblabs** [comment]
I see you made a few more commits since saying it was all set. Just want to check in one more time that it's ready 😄

**Comment by uajqq** [comment]
Sorry, sorry, couldn't help myself. All done now, I swear...

**Pull request merged**
