### PR TITLE
Added support for GeoNet Earthquake server (NZ)

### PR DESCRIPTION
**Pull request by windcrusader**
Hi Pat,

I've made the changes for this now into the latest development branch. Hopefully it is all good to go.

### CODE REVIEW

**Comment by 41south** [comment]
Hi Brad, I've just update to version 1.2 here and don't seem to be getting the GeoNet data. I set the stale interval to 600 temporarily and the range to 2000km - which should have displayed the Te Anau one yesterday? Any thoughts? There is nothing in the Weewx log to say it is fetching the data or failing to either

**Comment by 41south** [comment]
Have been chatting with Pat, the json file looks to have good data in it, radius is set to 2000km which should have picked up the Te Anau quake, which is in the JSON file.

**Comment by 41south** [comment]
# Earthquake defaults
            earthquake_server = GeoNet
            earthquake_enabled = 1
            earthquake_maxradiuskm = 2000
            earthquake_stale = 60

**Comment by poblabs** [comment]
In the first array item in the earthquake.json, I can see the below snippet. So the data looks current. I'm not sure yet why it's not being added to the weewx_data.json for display on the front page. 

```
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    167.417984,
                    -45.06748962
                ]
            },
            "properties": {
                "publicID": "2020p717213",
                "time": "2020-09-22T08:51:14.555Z",
                "depth": 63.65653992,
                "magnitude": 4.93328996,
                "mmi": 4,
                "locality": "45 km north-west of Te Anau",
                "quality": "best"
            }
        },
```

**Comment by poblabs** [comment]
Able to replicate it - might have found it. Working on a fix

**Comment by poblabs** [comment]
@41south Fixed it in commit https://github.com/poblabs/weewx-belchertown/commit/3ce9c5c849917da6dfece25d5d373140cf6eee22

Download the [latest belchertown.py](https://raw.githubusercontent.com/poblabs/weewx-belchertown/master/bin/user/belchertown.py), replace it with yours, restart weewx.

**Comment by 41south** [comment]
Update done, Weewx restarted, unfortunately still no data showing

**Comment by 41south** [comment]
Hi team

Just wondering if there is any update on this issue?

**Comment by windcrusader** [comment]
Hi Colin,

Probably have to do some debugging on your setup here, as it is working
perfectly for me.

Brad.

**Comment by 41south** [comment]
Hi Brad

Yeah it's a strange one, Pat thought he had found a bug and the data is
being downloaded into the json file but it only ever displays that message
of No recent earthquake data available!

I'm around all day :)

Colin

**Comment by 41south** [comment]
Available via private email if you like

**Comment by 41south** [comment]
Hi Brad any update on a fix for my issue? It seems it only works for you
and if it's not going to be supported maybe it needs to be removed from the
code?

Cheers
Colin

**Comment by windcrusader** [comment]
Hi Colin,

Sorry I haven’t had a chance to investigate this yet. Let me have a look tonight to see if I can replicate the issue.

Regards,
Brad Henderson

**Comment by 41south** [comment]
Thanks Brad, very much appreciated 👍

Cheers
Colin

**Comment by windcrusader** [comment]
Hi Colin,

Ok, so I updated my Belchertown skin to the latest version (from the
master) and the earthquake stuff is working perfectly for me still on my
site.

I am still running weewx 4.0.0, so I wonder if this could have something to
do with why you are getting problems? What version of weewx are you running?

Cheers,
Brad.

**Comment by 41south** [comment]
Hmm, well I'm on the same here too Weewx 4.0.0 and Skin 1.2

My site is 41south.nz. I assume there is nothing other than the conf file
to set up? Pat did think he had found a problem but it's still not working
and there are no errors either.

What does your conf file look like? I assume you have the settings in
weewx.conf

Cheers
Colin

**Comment by windcrusader** [comment]
Hi Colin,

Attached is my config file.

Can you check something else for me? I'd like to know if your setup is
actually pulling down the data from GeoNet. There should be a file called
"earthquake.json" stored in "public_html/json". This is the file that
"Belchertown.py" periodically updates. Can you check if it is being
updated? This should help isolate the issue.

Regards,
Brad

**Comment by 41south** [comment]
The json file has data, you can see it here
http://41south.nz/json/earthquake.json

I'll check my config against yours

**Comment by 41south** [comment]
Oh and no config file in the email :)

**Comment by windcrusader** [comment]
That's weird, I attached it. Here it is again.

Brad.

**Pull request merged**
