### PR TITLE
Added kiosk page

### PR DESCRIPTION
**Pull request by ThePeePs**
While the Pi Console page is nice, I was looking for something that had a bit more information on it that I could have in my kitchen.  So I came up with this "kiosk page". It's a "stripped down" version of the home page, but made to fit on a 1280x800 screen.  If there is anything you would like to change or add, please let me know.

### CODE REVIEW

**Comment by michaelundwd** [comment]
Any chance of a screenshot or a link to your website, so we can see it in 1280*800?

**Comment by ThePeePs** [comment]
I've added a screenshot, but didn't add it to the readme, since the path to the image doesn't exist yet in the master branch. if this PR is merged, the readme can then get updated.

**Comment by trobnc** [comment]
Made all the changes you posted for this but getting the following error from syslog:

`Mar 17 09:35:19 raspberrypi weewx[13242] INFO user.belchertown: version 1.3b1
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine: Caught unrecoverable exception in generator 'weewx.cheetahgenerator.CheetahGenerator'
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****  local variable 'mqtt_websockets_port_kiosk' referenced before assignment
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****  Traceback (most recent call last):
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 197, in run
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      obj.start()
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/reportengine.py", line 378, in start
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      self.run()
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 169, in run
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      ngen = self.generate(gen_dict[section_name], section_name, self.gen_ts)
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 229, in generate
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], subsection, gen_ts)
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 229, in generate
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      ngen += self.generate(section[subsection], subsection, gen_ts)
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 321, in generate
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      _filename))
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 411, in _getSearchList
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      search_list += obj.get_extension_list(timespan, db_lookup)
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****    File "/usr/share/weewx/user/belchertown.py", line 1958, in get_extension_list
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****      "mqtt_websockets_port_kiosk": mqtt_websockets_port_kiosk,
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****  UnboundLocalError: local variable 'mqtt_websockets_port_kiosk' referenced before assignment
Mar 17 09:35:19 raspberrypi weewx[13242] ERROR weewx.reportengine:         ****  Generator terminated
Mar 17 09:35:19 raspberrypi weewx[13242] INFO weewx.reportengine: Copied 38 files to /var/www/html/weewx/belchertown`

**Comment by ThePeePs** [comment]
Added on more fix for the JS file, that I missed (amateur hour over here, lol)  This should should resolve the rest of the MQTT bugs.

**Comment by trobnc** [comment]
Looks like I'm getting an error with the index.html.tmpl file which I don't remember changing. Here's the error:

Mar 21 09:45:20 raspberrypi weewx[19038] INFO user.belchertown: version 1.3b1
Mar 21 09:45:23 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/index.html.tmpl
Mar 21 09:45:23 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/index.html.tmpl
Mar 21 09:45:23 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:23 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/about/index.html.tmpl
Mar 21 09:45:23 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/about/index.html.tmpl
Mar 21 09:45:23 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/graphs/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/graphs/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/records/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/records/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/reports/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/reports/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/pi/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/pi/index.html.tmpl
Mar 21 09:45:24 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:25 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: Parse error while evaluating file /etc/weewx/skins/Belchertown/kiosk.html.tmpl
Mar 21 09:45:25 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Ignoring template /etc/weewx/skins/Belchertown/kiosk.html.tmpl
Mar 21 09:45:25 raspberrypi weewx[19038] ERROR weewx.cheetahgenerator: **** Reason: #012#012Some #directives are missing their corresponding #end ___ tag: if, if, if, if#012Line 210, column 11 in file /etc/weewx/skins/Belchertown/header.html.tmpl#012#012Line|Cheetah Code#012----|-------------------------------------------------------------#012207 |                </div>#012208 |            </header>#012209 |            #end if#012210 |    #end if#012               ^
Mar 21 09:45:25 raspberrypi weewx[19038] INFO weewx.cheetahgenerator: Generated 5 files for report Belchertown in 5.36 seconds
Mar 21 09:45:25 raspberrypi weewx[19038] INFO weewx.reportengine: Copied 39 files to /var/www/html/weewx/belchertown

**Comment by trobnc** [comment]
Okay, sorry had an error in the header.html.tmpl file. Seems to be running fine now.

**Comment by roe-dl** [comment]
I looked through the changes, and I would comment, that it is not generally useful to include `inTemp` etc. in `weewx_data.json.tmpl`. If the website is presented to the public it should not contain that private values as room temperature.

**Comment by ThePeePs** [comment]
@roe-dl The idea behind having the kiosk page, would be for setting up for "private viewing" like having it in the kitchen of your house, as to provide more info then the "pi console" page.  Apache or Nginx can be configured deny access to that page from the public internet.
Also, as stated in the readme, the kiosk can be configured to have the AQI instead of the inside temp/humidity, if one wishes to have the page publicly accessible, and/or doesn't want/need the inside information.

**Comment by roe-dl** [comment]
@ThePeePs You can enable or disable the kiosk page, but in both cases `weewx_data.json` contains the private values. So I guess you want to surround those observation types in `weewx_data.json.tmpl` by some `#if`-`#end if` statement.

**Comment by ThePeePs** [comment]
Just added an If for the inside data points for the data json file. If AQI is enabled for the kiosk page, the inside temp/humidity are not put into the json file.

TODO: make the inside data a separate json file, will require JS ajax changes

**Comment by ThePeePs** [comment]
In looking at a few other's websites that are publicly accessible (via [weewx's page](http://weewx.com/stations.html) page) it seems some people openly display their inside temperature and humidity, either in the observation pane or in charts on their home pages.  
I've updated the readme to note that this data will be in the json file if they decide to display it on the kiosk page. (in the event that not everyone reads though the comments of PR's)
I also put a TODO to have this data, and any other data that some might want to keep on private pages,  in it's own json file.  I'll try to update the ajax functions, but my JavaScript experience is limited, and I feel that that should be it's own PR.

@roe-dl sorry for the confusion earlier.

**Comment by ThePeePs** [comment]
@poblabs, I know this PR is kinda "out of the blue", just as a reference, I'm the one that talked about doing this kinda thing back in issue #283, but then work and life happened, and I wasn't able to get back to this till now. 

There also was also #711 of people looking for a bigger kiosk layout, tho this might be too much for a 7 inch display, it might be the kinda thing some people are looking for.

I'd love to get your thoughts on it.

**Comment by poblabs** [comment]
@ThePeePs No worries about being out of the blue. Same as you, life keeps happening and my kids don't give me much free time 😄 I think the bigger kiosk layout is a welcomed addition. Does the Pi page still fit too? I haven't had a close look at it. Do you have pictures/screenshots? Might be easier for quick glance at the change in layout

**Comment by ThePeePs** [comment]
I do have a [screenshot](https://github.com/ThePeePs/weewx-belchertown/blob/kiosk-page/assets/kiosk.png) in the PR. I didn't change anything on your original Pi page. That was my original thought, but changed direction when I thought of including the forecast as well.
Just did a quick look at [adafruit's](https://www.adafruit.com/category/400) Pi display offerings, and most of the 5-7 inch displays are either 800x480, 1024x600, or 1280x800.  My PR is geared for a 1280x800 display. I could in the future look at doing a page with just little more info then the current Pi page for the lower res display's if there enough people are/want to use them.

**Comment by poblabs** [comment]
@ThePeePs So I'm late to getting to this one and now there's conflicts with the main branch. Can you rebase your branch and re-submit the pull request so it has the latest version of everything?

**Comment by ThePeePs** [comment]
sure, not a problem

**Comment by ThePeePs** [comment]
I was able to resolve the conflict.

**Pull request merged**
