### PR TITLE
Removed iPad CSS section

### PR DESCRIPTION
**Pull request by uajqq**

### CODE REVIEW

**Review by ArendPWS — CHANGES_REQUESTED** [review]
Can't find the closing */ of the block comment, but perhaps I overlook.

**Comment by uajqq** [comment]
It seemed not to need one based on my testing, so I left it out for simplicity.

**Comment by ArendPWS** [comment]
In this case it might work, but you allways have to close your comment (out). This is best practice and avoids issues with the code later on.

**Comment by uajqq** [comment]
Done

**Pull request closed without merging**
